// VAST extensions controller service.
//
// Served by the Go extensions-controller on a unix socket shared with the
// Python CSI plugin container.  Python connects as a gRPC client to query and
// control operations managed by the controller — without needing direct
// Kubernetes API access.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: vast_extensions.proto

package extensionsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailoverType describes how a failover should be executed.
type FailoverType int32

const (
	FailoverType_FAILOVER_TYPE_UNGRACEFUL FailoverType = 0
	FailoverType_FAILOVER_TYPE_GRACEFUL   FailoverType = 1
)

// Enum value maps for FailoverType.
var (
	FailoverType_name = map[int32]string{
		0: "FAILOVER_TYPE_UNGRACEFUL",
		1: "FAILOVER_TYPE_GRACEFUL",
	}
	FailoverType_value = map[string]int32{
		"FAILOVER_TYPE_UNGRACEFUL": 0,
		"FAILOVER_TYPE_GRACEFUL":   1,
	}
)

func (x FailoverType) Enum() *FailoverType {
	p := new(FailoverType)
	*p = x
	return p
}

func (x FailoverType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailoverType) Descriptor() protoreflect.EnumDescriptor {
	return file_vast_extensions_proto_enumTypes[0].Descriptor()
}

func (FailoverType) Type() protoreflect.EnumType {
	return &file_vast_extensions_proto_enumTypes[0]
}

func (x FailoverType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailoverType.Descriptor instead.
func (FailoverType) EnumDescriptor() ([]byte, []int) {
	return file_vast_extensions_proto_rawDescGZIP(), []int{0}
}

type GetReplicationTenantRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage_class is the Kubernetes StorageClass name to resolve.
	StorageClass  string `protobuf:"bytes,1,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationTenantRequest) Reset() {
	*x = GetReplicationTenantRequest{}
	mi := &file_vast_extensions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationTenantRequest) ProtoMessage() {}

func (x *GetReplicationTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vast_extensions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationTenantRequest.ProtoReflect.Descriptor instead.
func (*GetReplicationTenantRequest) Descriptor() ([]byte, []int) {
	return file_vast_extensions_proto_rawDescGZIP(), []int{0}
}

func (x *GetReplicationTenantRequest) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

type GetReplicationTenantResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage_class echoes the requested StorageClass name.
	StorageClass string `protobuf:"bytes,1,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	// tenant_guid is the GUID of the VAST tenant associated with this
	// StorageClass.
	TenantGuid    string `protobuf:"bytes,2,opt,name=tenant_guid,json=tenantGuid,proto3" json:"tenant_guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationTenantResponse) Reset() {
	*x = GetReplicationTenantResponse{}
	mi := &file_vast_extensions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationTenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationTenantResponse) ProtoMessage() {}

func (x *GetReplicationTenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vast_extensions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationTenantResponse.ProtoReflect.Descriptor instead.
func (*GetReplicationTenantResponse) Descriptor() ([]byte, []int) {
	return file_vast_extensions_proto_rawDescGZIP(), []int{1}
}

func (x *GetReplicationTenantResponse) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *GetReplicationTenantResponse) GetTenantGuid() string {
	if x != nil {
		return x.TenantGuid
	}
	return ""
}

type GetReplicationInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage_class is the Kubernetes StorageClass name to look up.
	StorageClass string `protobuf:"bytes,1,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	// namespace limits the search to a specific namespace.
	// Leave empty to search across all namespaces.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationInfoRequest) Reset() {
	*x = GetReplicationInfoRequest{}
	mi := &file_vast_extensions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationInfoRequest) ProtoMessage() {}

func (x *GetReplicationInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vast_extensions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationInfoRequest.ProtoReflect.Descriptor instead.
func (*GetReplicationInfoRequest) Descriptor() ([]byte, []int) {
	return file_vast_extensions_proto_rawDescGZIP(), []int{2}
}

func (x *GetReplicationInfoRequest) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *GetReplicationInfoRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type GetReplicationInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resource_name is the name of the owning VastStorageClassReplication or
	// VastVolumeReplication object.
	ResourceName string `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	// namespace is the namespace of the owning object.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// resource_kind is either "VastStorageClassReplication" or
	// "VastVolumeReplication".
	ResourceKind string `protobuf:"bytes,3,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	// is_primary is true when storage_class equals the spec.primaryStorageClass
	// of the owning object.
	IsPrimary bool `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	// storage_classes is the full list of StorageClass names that participate
	// in this replication group (i.e. spec.storageClasses of the owner).
	StorageClasses []string `protobuf:"bytes,5,rep,name=storage_classes,json=storageClasses,proto3" json:"storage_classes,omitempty"`
	// failover_type is the failover type configured on the owning resource
	// (ungraceful or graceful).
	FailoverType  FailoverType `protobuf:"varint,6,opt,name=failover_type,json=failoverType,proto3,enum=vastextensions.v1.FailoverType" json:"failover_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReplicationInfoResponse) Reset() {
	*x = GetReplicationInfoResponse{}
	mi := &file_vast_extensions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReplicationInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReplicationInfoResponse) ProtoMessage() {}

func (x *GetReplicationInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vast_extensions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReplicationInfoResponse.ProtoReflect.Descriptor instead.
func (*GetReplicationInfoResponse) Descriptor() ([]byte, []int) {
	return file_vast_extensions_proto_rawDescGZIP(), []int{3}
}

func (x *GetReplicationInfoResponse) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *GetReplicationInfoResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetReplicationInfoResponse) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *GetReplicationInfoResponse) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *GetReplicationInfoResponse) GetStorageClasses() []string {
	if x != nil {
		return x.StorageClasses
	}
	return nil
}

func (x *GetReplicationInfoResponse) GetFailoverType() FailoverType {
	if x != nil {
		return x.FailoverType
	}
	return FailoverType_FAILOVER_TYPE_UNGRACEFUL
}

var File_vast_extensions_proto protoreflect.FileDescriptor

const file_vast_extensions_proto_rawDesc = "" +
	"\n" +
	"\x15vast_extensions.proto\x12\x11vastextensions.v1\"B\n" +
	"\x1bGetReplicationTenantRequest\x12#\n" +
	"\rstorage_class\x18\x01 \x01(\tR\fstorageClass\"d\n" +
	"\x1cGetReplicationTenantResponse\x12#\n" +
	"\rstorage_class\x18\x01 \x01(\tR\fstorageClass\x12\x1f\n" +
	"\vtenant_guid\x18\x02 \x01(\tR\n" +
	"tenantGuid\"^\n" +
	"\x19GetReplicationInfoRequest\x12#\n" +
	"\rstorage_class\x18\x01 \x01(\tR\fstorageClass\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\x92\x02\n" +
	"\x1aGetReplicationInfoResponse\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12#\n" +
	"\rresource_kind\x18\x03 \x01(\tR\fresourceKind\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\x12'\n" +
	"\x0fstorage_classes\x18\x05 \x03(\tR\x0estorageClasses\x12D\n" +
	"\rfailover_type\x18\x06 \x01(\x0e2\x1f.vastextensions.v1.FailoverTypeR\ffailoverType*H\n" +
	"\fFailoverType\x12\x1c\n" +
	"\x18FAILOVER_TYPE_UNGRACEFUL\x10\x00\x12\x1a\n" +
	"\x16FAILOVER_TYPE_GRACEFUL\x10\x012\xfc\x01\n" +
	"\x0eVastExtensions\x12w\n" +
	"\x14GetReplicationTenant\x12..vastextensions.v1.GetReplicationTenantRequest\x1a/.vastextensions.v1.GetReplicationTenantResponse\x12q\n" +
	"\x12GetReplicationInfo\x12,.vastextensions.v1.GetReplicationInfoRequest\x1a-.vastextensions.v1.GetReplicationInfoResponseB`Z^github.com/vast-data/vast-csi/extensions-controller/internal/server/extensions/v1;extensionsv1b\x06proto3"

var (
	file_vast_extensions_proto_rawDescOnce sync.Once
	file_vast_extensions_proto_rawDescData []byte
)

func file_vast_extensions_proto_rawDescGZIP() []byte {
	file_vast_extensions_proto_rawDescOnce.Do(func() {
		file_vast_extensions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vast_extensions_proto_rawDesc), len(file_vast_extensions_proto_rawDesc)))
	})
	return file_vast_extensions_proto_rawDescData
}

var file_vast_extensions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_vast_extensions_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_vast_extensions_proto_goTypes = []any{
	(FailoverType)(0),                    // 0: vastextensions.v1.FailoverType
	(*GetReplicationTenantRequest)(nil),  // 1: vastextensions.v1.GetReplicationTenantRequest
	(*GetReplicationTenantResponse)(nil), // 2: vastextensions.v1.GetReplicationTenantResponse
	(*GetReplicationInfoRequest)(nil),    // 3: vastextensions.v1.GetReplicationInfoRequest
	(*GetReplicationInfoResponse)(nil),   // 4: vastextensions.v1.GetReplicationInfoResponse
}
var file_vast_extensions_proto_depIdxs = []int32{
	0, // 0: vastextensions.v1.GetReplicationInfoResponse.failover_type:type_name -> vastextensions.v1.FailoverType
	1, // 1: vastextensions.v1.VastExtensions.GetReplicationTenant:input_type -> vastextensions.v1.GetReplicationTenantRequest
	3, // 2: vastextensions.v1.VastExtensions.GetReplicationInfo:input_type -> vastextensions.v1.GetReplicationInfoRequest
	2, // 3: vastextensions.v1.VastExtensions.GetReplicationTenant:output_type -> vastextensions.v1.GetReplicationTenantResponse
	4, // 4: vastextensions.v1.VastExtensions.GetReplicationInfo:output_type -> vastextensions.v1.GetReplicationInfoResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_vast_extensions_proto_init() }
func file_vast_extensions_proto_init() {
	if File_vast_extensions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vast_extensions_proto_rawDesc), len(file_vast_extensions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vast_extensions_proto_goTypes,
		DependencyIndexes: file_vast_extensions_proto_depIdxs,
		EnumInfos:         file_vast_extensions_proto_enumTypes,
		MessageInfos:      file_vast_extensions_proto_msgTypes,
	}.Build()
	File_vast_extensions_proto = out.File
	file_vast_extensions_proto_goTypes = nil
	file_vast_extensions_proto_depIdxs = nil
}
