// VAST extensions controller service.
//
// Served by the Go extensions-controller.  Python CSI plugin containers connect
// as gRPC clients over TCP (cluster-wide Service) or a co-located unix socket.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.0
// source: vast_extensions.proto

package extensionsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VastExtensions_GetReplicationTenant_FullMethodName  = "/vastextensions.v1.VastExtensions/GetReplicationTenant"
	VastExtensions_GetReplicationInfo_FullMethodName    = "/vastextensions.v1.VastExtensions/GetReplicationInfo"
	VastExtensions_ResolveSecret_FullMethodName         = "/vastextensions.v1.VastExtensions/ResolveSecret"
	VastExtensions_ResolveCOSIBucketAuth_FullMethodName = "/vastextensions.v1.VastExtensions/ResolveCOSIBucketAuth"
)

// VastExtensionsClient is the client API for VastExtensions service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VastExtensions exposes management operations to non-native clients
type VastExtensionsClient interface {
	// GetReplicationTenant resolves the VAST tenant GUID for the given
	// Kubernetes StorageClass.  The GUID is looked up from the VAST VMS REST
	// API via the VIP pool referenced by the StorageClass parameters
	// (vip_pool_name or vip_pool_fqdn).
	GetReplicationTenant(ctx context.Context, in *GetReplicationTenantRequest, opts ...grpc.CallOption) (*GetReplicationTenantResponse, error)
	// GetReplicationInfo - return replication related info.
	GetReplicationInfo(ctx context.Context, in *GetReplicationInfoRequest, opts ...grpc.CallOption) (*GetReplicationInfoResponse, error)
	// ResolveSecret fetches a Kubernetes Secret and returns its data as a
	// key/value map, matching CSI CreateVolumeRequest.secrets as populated by
	// the external-provisioner sidecar.
	ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error)
	// ResolveCOSIBucketAuth resolves VMS credentials for a COSI bucket_id by
	// looking up the Bucket CR and resolving vastdata.com/secret-* parameters.
	ResolveCOSIBucketAuth(ctx context.Context, in *ResolveCOSIBucketAuthRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error)
}

type vastExtensionsClient struct {
	cc grpc.ClientConnInterface
}

func NewVastExtensionsClient(cc grpc.ClientConnInterface) VastExtensionsClient {
	return &vastExtensionsClient{cc}
}

func (c *vastExtensionsClient) GetReplicationTenant(ctx context.Context, in *GetReplicationTenantRequest, opts ...grpc.CallOption) (*GetReplicationTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationTenantResponse)
	err := c.cc.Invoke(ctx, VastExtensions_GetReplicationTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastExtensionsClient) GetReplicationInfo(ctx context.Context, in *GetReplicationInfoRequest, opts ...grpc.CallOption) (*GetReplicationInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReplicationInfoResponse)
	err := c.cc.Invoke(ctx, VastExtensions_GetReplicationInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastExtensionsClient) ResolveSecret(ctx context.Context, in *ResolveSecretRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretResponse)
	err := c.cc.Invoke(ctx, VastExtensions_ResolveSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vastExtensionsClient) ResolveCOSIBucketAuth(ctx context.Context, in *ResolveCOSIBucketAuthRequest, opts ...grpc.CallOption) (*ResolveSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSecretResponse)
	err := c.cc.Invoke(ctx, VastExtensions_ResolveCOSIBucketAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VastExtensionsServer is the server API for VastExtensions service.
// All implementations must embed UnimplementedVastExtensionsServer
// for forward compatibility.
//
// VastExtensions exposes management operations to non-native clients
type VastExtensionsServer interface {
	// GetReplicationTenant resolves the VAST tenant GUID for the given
	// Kubernetes StorageClass.  The GUID is looked up from the VAST VMS REST
	// API via the VIP pool referenced by the StorageClass parameters
	// (vip_pool_name or vip_pool_fqdn).
	GetReplicationTenant(context.Context, *GetReplicationTenantRequest) (*GetReplicationTenantResponse, error)
	// GetReplicationInfo - return replication related info.
	GetReplicationInfo(context.Context, *GetReplicationInfoRequest) (*GetReplicationInfoResponse, error)
	// ResolveSecret fetches a Kubernetes Secret and returns its data as a
	// key/value map, matching CSI CreateVolumeRequest.secrets as populated by
	// the external-provisioner sidecar.
	ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error)
	// ResolveCOSIBucketAuth resolves VMS credentials for a COSI bucket_id by
	// looking up the Bucket CR and resolving vastdata.com/secret-* parameters.
	ResolveCOSIBucketAuth(context.Context, *ResolveCOSIBucketAuthRequest) (*ResolveSecretResponse, error)
	mustEmbedUnimplementedVastExtensionsServer()
}

// UnimplementedVastExtensionsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVastExtensionsServer struct{}

func (UnimplementedVastExtensionsServer) GetReplicationTenant(context.Context, *GetReplicationTenantRequest) (*GetReplicationTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReplicationTenant not implemented")
}
func (UnimplementedVastExtensionsServer) GetReplicationInfo(context.Context, *GetReplicationInfoRequest) (*GetReplicationInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReplicationInfo not implemented")
}
func (UnimplementedVastExtensionsServer) ResolveSecret(context.Context, *ResolveSecretRequest) (*ResolveSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSecret not implemented")
}
func (UnimplementedVastExtensionsServer) ResolveCOSIBucketAuth(context.Context, *ResolveCOSIBucketAuthRequest) (*ResolveSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveCOSIBucketAuth not implemented")
}
func (UnimplementedVastExtensionsServer) mustEmbedUnimplementedVastExtensionsServer() {}
func (UnimplementedVastExtensionsServer) testEmbeddedByValue()                        {}

// UnsafeVastExtensionsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VastExtensionsServer will
// result in compilation errors.
type UnsafeVastExtensionsServer interface {
	mustEmbedUnimplementedVastExtensionsServer()
}

func RegisterVastExtensionsServer(s grpc.ServiceRegistrar, srv VastExtensionsServer) {
	// If the following call panics, it indicates UnimplementedVastExtensionsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VastExtensions_ServiceDesc, srv)
}

func _VastExtensions_GetReplicationTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastExtensionsServer).GetReplicationTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VastExtensions_GetReplicationTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastExtensionsServer).GetReplicationTenant(ctx, req.(*GetReplicationTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastExtensions_GetReplicationInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReplicationInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastExtensionsServer).GetReplicationInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VastExtensions_GetReplicationInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastExtensionsServer).GetReplicationInfo(ctx, req.(*GetReplicationInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastExtensions_ResolveSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastExtensionsServer).ResolveSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VastExtensions_ResolveSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastExtensionsServer).ResolveSecret(ctx, req.(*ResolveSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VastExtensions_ResolveCOSIBucketAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveCOSIBucketAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VastExtensionsServer).ResolveCOSIBucketAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VastExtensions_ResolveCOSIBucketAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VastExtensionsServer).ResolveCOSIBucketAuth(ctx, req.(*ResolveCOSIBucketAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VastExtensions_ServiceDesc is the grpc.ServiceDesc for VastExtensions service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VastExtensions_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vastextensions.v1.VastExtensions",
	HandlerType: (*VastExtensionsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetReplicationTenant",
			Handler:    _VastExtensions_GetReplicationTenant_Handler,
		},
		{
			MethodName: "GetReplicationInfo",
			Handler:    _VastExtensions_GetReplicationInfo_Handler,
		},
		{
			MethodName: "ResolveSecret",
			Handler:    _VastExtensions_ResolveSecret_Handler,
		},
		{
			MethodName: "ResolveCOSIBucketAuth",
			Handler:    _VastExtensions_ResolveCOSIBucketAuth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vast_extensions.proto",
}
