apiVersion: v2
name: vastcsi-gke
description: Helm chart for Deployment of VAST Container Storage Interface (CSI) on GKE
type: application
version: "2.7.0" #  will be updated by the release ci
keywords:
  - vast
  - csi
  - driver
  - vastdata
  - csi-driver
  - gke
icon: "https://uploads.vastdata.com/2020/04/vast-white-1.svg"
home: "https://support.vastdata.com/s/topic/0TOV400000026yzOAA/vast-csi-driver"
dependencies:
  - name: vast-common
    version: "1.0.0"
    repository: "https://vast-data.github.io/vast-csi"
