kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-static
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pv-static
  storageClassName: vastdata-filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-static
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: vastdata-filesystem
  csi:
    driver: csi.vastdata.com
    volumeHandle: 3:/test
    volumeAttributes:
      vip_pool_name: vippool-1
