deletionViewPolicy: default
deletionVipPool: vippool-1
endpoint: 172.31.50.142
imagePullPolicy: Always
secretName: vast-mgmt
truncateVolumeName: 64
verifySsl: false

storageClassDefaults:
  secretName: vast-mgmt
  secretNamespace: default
  mountOptions: ["proto=tcp,nfsvers=4.1 ,sec=sys"]

snapshotClassDefaults:
  secretName: vast-mgmt
  secretNamespace: default

storageClasses:
  vastdata-filesystem:
    ephemeralVolumeNameFormat: csi:{name}:{id}
    setDefaultStorageClass: true
    storagePath: /k8s
    viewPolicy: default
    vipPool: vippool-1
    volumeNameFormat: csi:{name}:{id}
    secretName: vast-mgmt

bucketClasses:
  vastdata-bucket:
    viewPolicy: s3_default_policy
    vipPool: vippool-1

image:
  csiVastPlugin:
    repository: fnn45/vast-csi
    tag: dev

# kubectl create secret generic vast-mgmt --from-literal=username='admin' --from-literal=password='123456' --from-literal=endpoint=172.31.50.142 --from-literal=tenant=default

controller:
#  nodeSelector:
#    "beta.kubernetes.io/arch": "amd64"
  dnsPolicy: ClusterFirstWithHostNet
#  runOnMaster: true
#  runOnControlPlane: true
#  tolerations:
#    - key: "node-role.kubernetes.io/master"
#      operator: "Exists"
#      effect: "NoSchedule"
#    - key: "node-role.kubernetes.io/controlplane"
#      operator: "Exists"
#      effect: "NoSchedule"
#    - key: "node-role.kubernetes.io/control-plane"
#      operator: "Exists"
#      effect: "NoSchedule"
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#          - matchExpressions:
#              - key: disktype
#                operator: In
#                values:
#                  - ssd


node:
#    nodeSelector:
#        "beta.kubernetes.io/arch": "amd64"
    dnsPolicy: ClusterFirstWithHostNet
#    tolerations:
#      - key: "node-role.kubernetes.io/master"
#        operator: "Exists"
#        effect: "NoSchedule"
#      - key: "node-role.kubernetes.io/controlplane"
#        operator: "Exists"
#        effect: "NoSchedule"
#      - key: "node-role.kubernetes.io/control-plane"
#        operator: "Exists"
#        effect: "NoSchedule"
#    affinity:
#      nodeAffinity:
#        requiredDuringSchedulingIgnoredDuringExecution:
#          nodeSelectorTerms:
#            - matchExpressions:
#                - key: disktype
#                  operator: In
#                  values:
#                    - ssd
