name: "csi.vastdata.com"

# Namespace for csi driver operator installation.
# If a namespace is not specified during the installation of the CSI driver operator,
# it will default to the namespace of the Helm release.
namespace: null

# CI pipe for testing builds
ciPipe: null

# imagePullSecret for testing builds
imagePullSecret: null

# Operator manager image
managerImage: docker.io/vastdataorg/csi@sha256:7cd73d9cc3e35ef74ac0efd1e7d4c8a88100c8c259acbbaf9e548dc13e645139
# Operator proxy image
proxyImage: docker.io/kubebuilder/kube-rbac-proxy@sha256:a2523c532c0c3d51a5396a901d7ded23e402a9a1492c783aae27af6d0c1d2ec5

# Used in OpenShift UI for driver installation.
suggestedNamespace: "vast-csi"

# Operator documentation link
operatorDocs: "https://support.vastdata.com/s/document-item?bundleId=vast-csi-driver-2.6-administrator-s-guide&topicId=deploying-vast-csi-driver/deploying-vast-csi-driver-on-openshift-with-vast-csi-operator.html&_LANG=enus"

overrides:
  csiVastPlugin:
    repository: docker.io/vastdataorg/csi@sha256:0a4af94e3d5e03d7ecd294305b17b379d6fc99183acbf0588bbfecea79a8bff6
  csiAttacher:
    repository: registry.k8s.io/sig-storage/csi-attacher@sha256:b4d611100ece2f9bc980d1cb19c2285b8868da261e3b1ee8f45448ab5512ab94
  csiNodeDriverRegistrar:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar@sha256:f25af73ee708ff9c82595ae99493cdef9295bd96953366cddf36305f82555dac
  csiProvisioner:
    repository: registry.k8s.io/sig-storage/csi-provisioner@sha256:405a14e1aa702f7ea133cea459e8395fe40a6125c088c55569e696d48e1bd385
  csiResizer:
    repository: registry.k8s.io/sig-storage/csi-resizer@sha256:a541e6cc2d8b011bb21b1d4ffec6b090e85270cce6276ee302d86153eec0af43
  csiSnapshotter:
    repository: registry.k8s.io/sig-storage/csi-snapshotter@sha256:42af0929bcd60a43499825c078a60ff0534e08af8fbeb283aa391be40feb9f3e
  csiAddonsSidecar:
    repository: quay.io/csiaddons/k8s-sidecar@sha256:208b4d21b125f4ef9d0ea4082bdf5aeafc9771e0e233e7c60e50e8bf3f5cb3db
  csiAddonsController:
    repository: quay.io/csiaddons/k8s-controller@sha256:318b6dd286db67bee59f2fc2ee0cc9a21302c9f90a43a8d2bda2fdaf78a1ae5b
  vastExtensionController:
    repository: docker.io/vastdataorg/csi@sha256:4ee38a27ee19d033a6cca47cd442855159eeb4645c83fa659bee8d5d8286dbf2

# Disable if you don't have intention to use snapshots (Enabled by default)
installSnapshotCRDS: true

####################
# BUNDLE SETTINGS
####################
# Build based on the OLM bundle: https://olm.operatorframework.io/
# Do not change this unless you fully understand all implications.
# Enabling this option (true) will generate a different template. It skips all roles, role bindings, and the operator manager deployment.
# Instead, these templates become part of the installation section of the ClusterServiceVersion.
# This option is intended for clusters with OLM installed, where the intention is to install and manage the operator via OLM.
olmBuild: false
maturity: "stable"

# The version that this operator replaces in the upgrade graph.
# This is required for OLM to understand the operator upgrade path.
# Example: "2.6.3" will generate "replaces: vast-csi-operator.v2.6.3"
# Leave empty for the first release or if no replacement is needed.
replacesVersion: "2.6.5"
