  description: |-
    The VastData CSI Driver integrates seamlessly with Kubernetes, adhering to CNCF standards and
    specifically designed for Vast storage systems. It enhances Kubernetes deployments at large
    scales, including support for Red Hat OpenShift.
    ### Installation
    Refer to the VastData Operator for Kubernetes [official documentation](https://support.vastdata.com/s/topic/0TOV40000000TwTOAU/vast-csi-driver-23-administrators-guide).