# Use the 'create api' subcommand to add watches to this file.
- group: storage.vastdata.com
  version: v1
  kind: VastCSIDriver
  chart: helm-charts/vastcsidriver
- group: storage.vastdata.com
  version: v1
  kind: VastStorage
  chart: helm-charts/vaststorage
- group: storage.vastdata.com
  version: v1
  kind: VastCluster
  chart: helm-charts/vastcluster
# +kubebuilder:scaffold:watch
