apiVersion: storage.vastdata.com/v1
kind: VastCSIDriver
metadata:
  name: csi.vastdata.com
  namespace: vast-csi
spec:
  driverType: "nfs"
  image:
    csiVastPlugin:
      repository: docker.io/vastdataorg/csi:v2.6.3
