apiVersion: storage.vastdata.com/v1
kind: VastStorage
metadata:
  name: vastdata-filesystem
  namespace: vast-csi
spec:
  driverType: "nfs"
  provisioner: "csi.vastdata.com"
  secretName: vastcluster
  secretNamespace: vast-csi
  storagePath: "/k8s"
  viewPolicy: "default"
  vipPool: "vippool-1"
  allowVolumeExpansion: true
  createSnapshotClass: false
