apiVersion: storage.vastdata.com/v1
kind: VastStorage
metadata:
  name: storage
spec:
  clusterName: "cluster"
  storageClass:
    name: "vastdata-filesystem"
    storagePath: "/k8s"
    viewPolicy: "default"
    vipPool: "vippool-1"
  snapshotClass:
    name: "vastdata-snapshot"
    snapshotNameFormat: csi:{namespace}:{name}:{id}
    deletionPolicy: Delete
    setDefaultSnapshotClass: false