apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-vast-extensions-manager-sa
  namespace: {{ include "vastextensionsmanager.namespace" . }}
  labels:
{{- include "vastextensionsmanager.labels" . | nindent 4 }}
