apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-vast-extensions-manager-sa
  namespace: {{ include "vast.common.namespace" . }}
  labels:
{{- include "vast.common.labels" . | nindent 4 }}
    app.kubernetes.io/component: vast-extensions-manager