{{- $grpcPort := include "vastextensionsmanager.grpcPort" . -}}
{{- $ns := include "vast.common.namespace" . | trimAll "\"" }}
{{- $svcName := include "vastextensionsmanager.grpcServiceName" . }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $svcName }}
  namespace: {{ $ns }}
  labels:
{{- include "vast.common.labels" . | nindent 4 }}
    app.kubernetes.io/component: vast-extensions-manager
spec:
  ports:
    - port: {{ $grpcPort }}
      targetPort: grpc
      name: grpc
      protocol: TCP
  selector:
    app: {{ include "vastextensionsmanager.deploymentName" . }}
