{{- if .Values.rbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-vast-provisioner-binding
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vast-controller-sa
    namespace: {{ include "vast.common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-vast-provisioner-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-vast-attacher-binding
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vast-controller-sa
    namespace: {{ include "vast.common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-vast-attacher-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-resizer-role
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vast-controller-sa
    namespace: {{ include "vast.common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-external-resizer-runner
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.extensions.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-csi-addons-binding
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vast-extension-controller-sa
    namespace: {{ include "vast.common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-csi-addons-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- if .Values.extensions.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-vast-extension-controller-binding
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-vast-extension-controller-sa
    namespace: {{ include "vast.common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-vast-extension-controller-role
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end -}}
