{{- $extensions := .Values.extensions -}}
{{- $webhook := $extensions.webhook -}}
{{- if and $extensions.enabled (not $webhook.certManager.enabled) -}}
{{- $webhooks := list -}}
{{- if not $webhook.disablePvcLabelsWebhook -}}
{{- $webhooks = append $webhooks (dict
  "name" "pvc-label-injector.vastdata.com"
  "failurePolicy" ($webhook.failurePolicy | default "Fail")
  "path" "/mutate-pvc"
  "rules" (list (dict "apiGroups" (list "") "apiVersions" (list "v1") "operations" (list "CREATE") "resources" (list "persistentvolumeclaims")))
  "namespaceSelector" (dict "matchExpressions" (list (dict "key" "kubernetes.io/metadata.name" "operator" "NotIn" "values" (list "kube-system" "kube-public"))))
) -}}
{{- end -}}
{{- if not $webhook.disableVscrValidationWebhook -}}
{{- $webhooks = append $webhooks (dict
  "name" "vaststorageclassreplication.vastdata.com"
  "failurePolicy" ($webhook.failurePolicy | default "Fail")
  "timeoutSeconds" ($webhook.timeoutSeconds | default 30)
  "path" "/validate-vastdata-com-v1alpha1-vaststorageclassreplication"
  "rules" (list (dict "apiGroups" (list "vastdata.com") "apiVersions" (list "v1alpha1") "operations" (list "CREATE" "UPDATE") "resources" (list "vaststorageclassreplications")))
) -}}
{{- end -}}
{{- if not $webhook.disableVvrValidationWebhook -}}
{{- $webhooks = append $webhooks (dict
  "name" "vastvolumereplication.vastdata.com"
  "failurePolicy" ($webhook.failurePolicy | default "Fail")
  "timeoutSeconds" ($webhook.timeoutSeconds | default 30)
  "path" "/validate-vastdata-com-v1alpha1-vastvolumereplication"
  "rules" (list (dict "apiGroups" (list "vastdata.com") "apiVersions" (list "v1alpha1") "operations" (list "CREATE" "UPDATE") "resources" (list "vastvolumereplications")))
) -}}
{{- end -}}
{{ include "vast.common.resource.webhookCertificate" (dict
  "name" (printf "%s-vast-extension-controller-webhook" .Release.Name)
  "namespace" (include "vast.common.namespace" . | trimAll "\"")
  "caName" "vast-csi-webhook-ca"
  "labels" (include "vast.common.labels" .)
  "webhooks" $webhooks
) }}
{{- end }}
