{{/* ClusterRoleBindings for Vast CSI */}}

{{- $namespace := include "vastcsi.namespace" . }}
{{- $labels := include "vastcsi.labels" . | nindent 4 }}
{{- $releaseName := .Release.Name }}

{{- $bindings := (list "provisioner" "attacher" "resizer") }}

{{- range $index, $role := $bindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $releaseName }}-vast-{{ $role }}-binding
  labels:
    {{- $labels }}
subjects:
  - kind: ServiceAccount
    name: {{ $releaseName }}-vast-controller-sa
    namespace: {{ $namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $releaseName }}-vast-{{ $role }}-role
  apiGroup: rbac.authorization.k8s.io

---
{{ end }}

