
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-vast-controller-sa
  namespace: {{ include "vast.common.namespace" . }}
  labels:
{{- include "vast.common.labels" . | nindent 4 }}
    storage.vastdata.com/driverType: {{ .Values.driverType }}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-vast-node-sa
  namespace: {{ include "vast.common.namespace" . }}
  labels:
{{- include "vast.common.labels" . | nindent 4 }}
    storage.vastdata.com/driverType: {{ .Values.driverType }}