# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vast_csi.proto import addons_identity_pb2 as addons_identity__pb2


class IdentityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/identity.Identity/GetIdentity',
                request_serializer=addons_identity__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=addons_identity__pb2.GetIdentityResponse.FromString,
                )
        self.GetCapabilities = channel.unary_unary(
                '/identity.Identity/GetCapabilities',
                request_serializer=addons_identity__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=addons_identity__pb2.GetCapabilitiesResponse.FromString,
                )
        self.Probe = channel.unary_unary(
                '/identity.Identity/Probe',
                request_serializer=addons_identity__pb2.ProbeRequest.SerializeToString,
                response_deserializer=addons_identity__pb2.ProbeResponse.FromString,
                )


class IdentityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIdentity(self, request, context):
        """Get information about the CSI-Addons Node Plugin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Get capabilities of the CSI-Addons Node Plugin
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Probe(self, request, context):
        """Probe the plugin for readiness
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=addons_identity__pb2.GetIdentityRequest.FromString,
                    response_serializer=addons_identity__pb2.GetIdentityResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=addons_identity__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=addons_identity__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=addons_identity__pb2.ProbeRequest.FromString,
                    response_serializer=addons_identity__pb2.ProbeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identity.Identity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Identity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/identity.Identity/GetIdentity',
            addons_identity__pb2.GetIdentityRequest.SerializeToString,
            addons_identity__pb2.GetIdentityResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/identity.Identity/GetCapabilities',
            addons_identity__pb2.GetCapabilitiesRequest.SerializeToString,
            addons_identity__pb2.GetCapabilitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/identity.Identity/Probe',
            addons_identity__pb2.ProbeRequest.SerializeToString,
            addons_identity__pb2.ProbeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
