# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import identity_pb2 as identity__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in identity_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityStub(object):
    """Identity is the service that CSI-drivers MUST implement in order to be
    compatible with CSI-Addons specification. It provides the basic details that
    are needed by the CSI-Addons CO plugin to communicate with the CSI-driver
    and detects its supported features.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/identity.Identity/GetIdentity',
                request_serializer=identity__pb2.GetIdentityRequest.SerializeToString,
                response_deserializer=identity__pb2.GetIdentityResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/identity.Identity/GetCapabilities',
                request_serializer=identity__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=identity__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.Probe = channel.unary_unary(
                '/identity.Identity/Probe',
                request_serializer=identity__pb2.ProbeRequest.SerializeToString,
                response_deserializer=identity__pb2.ProbeResponse.FromString,
                _registered_method=True)


class IdentityServicer(object):
    """Identity is the service that CSI-drivers MUST implement in order to be
    compatible with CSI-Addons specification. It provides the basic details that
    are needed by the CSI-Addons CO plugin to communicate with the CSI-driver
    and detects its supported features.
    """

    def GetIdentity(self, request, context):
        """GetIdentity returns basic information about the side-car and CSI-driver.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """GetCapabilities returns the capabilities that the CSI-driver supports.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Probe(self, request, context):
        """Probe is called by the CO plugin to validate that the CSI-Addons Node is
        still healthy.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=identity__pb2.GetIdentityRequest.FromString,
                    response_serializer=identity__pb2.GetIdentityResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=identity__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=identity__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'Probe': grpc.unary_unary_rpc_method_handler(
                    servicer.Probe,
                    request_deserializer=identity__pb2.ProbeRequest.FromString,
                    response_serializer=identity__pb2.ProbeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'identity.Identity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('identity.Identity', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Identity(object):
    """Identity is the service that CSI-drivers MUST implement in order to be
    compatible with CSI-Addons specification. It provides the basic details that
    are needed by the CSI-Addons CO plugin to communicate with the CSI-driver
    and detects its supported features.
    """

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.Identity/GetIdentity',
            identity__pb2.GetIdentityRequest.SerializeToString,
            identity__pb2.GetIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.Identity/GetCapabilities',
            identity__pb2.GetCapabilitiesRequest.SerializeToString,
            identity__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Probe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/identity.Identity/Probe',
            identity__pb2.ProbeRequest.SerializeToString,
            identity__pb2.ProbeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
