# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerStub(object):
    """Controller holds the RPC methods for replication and all the methods it
    exposes should be idempotent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnableVolumeReplication = channel.unary_unary(
                '/replication.Controller/EnableVolumeReplication',
                request_serializer=replication__pb2.EnableVolumeReplicationRequest.SerializeToString,
                response_deserializer=replication__pb2.EnableVolumeReplicationResponse.FromString,
                _registered_method=True)
        self.DisableVolumeReplication = channel.unary_unary(
                '/replication.Controller/DisableVolumeReplication',
                request_serializer=replication__pb2.DisableVolumeReplicationRequest.SerializeToString,
                response_deserializer=replication__pb2.DisableVolumeReplicationResponse.FromString,
                _registered_method=True)
        self.PromoteVolume = channel.unary_unary(
                '/replication.Controller/PromoteVolume',
                request_serializer=replication__pb2.PromoteVolumeRequest.SerializeToString,
                response_deserializer=replication__pb2.PromoteVolumeResponse.FromString,
                _registered_method=True)
        self.DemoteVolume = channel.unary_unary(
                '/replication.Controller/DemoteVolume',
                request_serializer=replication__pb2.DemoteVolumeRequest.SerializeToString,
                response_deserializer=replication__pb2.DemoteVolumeResponse.FromString,
                _registered_method=True)
        self.ResyncVolume = channel.unary_unary(
                '/replication.Controller/ResyncVolume',
                request_serializer=replication__pb2.ResyncVolumeRequest.SerializeToString,
                response_deserializer=replication__pb2.ResyncVolumeResponse.FromString,
                _registered_method=True)
        self.GetVolumeReplicationInfo = channel.unary_unary(
                '/replication.Controller/GetVolumeReplicationInfo',
                request_serializer=replication__pb2.GetVolumeReplicationInfoRequest.SerializeToString,
                response_deserializer=replication__pb2.GetVolumeReplicationInfoResponse.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Controller holds the RPC methods for replication and all the methods it
    exposes should be idempotent.
    """

    def EnableVolumeReplication(self, request, context):
        """EnableVolumeReplication RPC call to enable the volume replication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisableVolumeReplication(self, request, context):
        """DisableVolumeReplication RPC call to disable the volume replication.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PromoteVolume(self, request, context):
        """PromoteVolume RPC call to promote the volume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DemoteVolume(self, request, context):
        """DemoteVolume RPC call to demote the volume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResyncVolume(self, request, context):
        """ResyncVolume RPC call to resync the volume.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetVolumeReplicationInfo(self, request, context):
        """GetVolumeReplicationInfo RPC call to get the volume replication
        information.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnableVolumeReplication': grpc.unary_unary_rpc_method_handler(
                    servicer.EnableVolumeReplication,
                    request_deserializer=replication__pb2.EnableVolumeReplicationRequest.FromString,
                    response_serializer=replication__pb2.EnableVolumeReplicationResponse.SerializeToString,
            ),
            'DisableVolumeReplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DisableVolumeReplication,
                    request_deserializer=replication__pb2.DisableVolumeReplicationRequest.FromString,
                    response_serializer=replication__pb2.DisableVolumeReplicationResponse.SerializeToString,
            ),
            'PromoteVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.PromoteVolume,
                    request_deserializer=replication__pb2.PromoteVolumeRequest.FromString,
                    response_serializer=replication__pb2.PromoteVolumeResponse.SerializeToString,
            ),
            'DemoteVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoteVolume,
                    request_deserializer=replication__pb2.DemoteVolumeRequest.FromString,
                    response_serializer=replication__pb2.DemoteVolumeResponse.SerializeToString,
            ),
            'ResyncVolume': grpc.unary_unary_rpc_method_handler(
                    servicer.ResyncVolume,
                    request_deserializer=replication__pb2.ResyncVolumeRequest.FromString,
                    response_serializer=replication__pb2.ResyncVolumeResponse.SerializeToString,
            ),
            'GetVolumeReplicationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetVolumeReplicationInfo,
                    request_deserializer=replication__pb2.GetVolumeReplicationInfoRequest.FromString,
                    response_serializer=replication__pb2.GetVolumeReplicationInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'replication.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('replication.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Controller holds the RPC methods for replication and all the methods it
    exposes should be idempotent.
    """

    @staticmethod
    def EnableVolumeReplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Controller/EnableVolumeReplication',
            replication__pb2.EnableVolumeReplicationRequest.SerializeToString,
            replication__pb2.EnableVolumeReplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DisableVolumeReplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Controller/DisableVolumeReplication',
            replication__pb2.DisableVolumeReplicationRequest.SerializeToString,
            replication__pb2.DisableVolumeReplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PromoteVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Controller/PromoteVolume',
            replication__pb2.PromoteVolumeRequest.SerializeToString,
            replication__pb2.PromoteVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DemoteVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Controller/DemoteVolume',
            replication__pb2.DemoteVolumeRequest.SerializeToString,
            replication__pb2.DemoteVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResyncVolume(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Controller/ResyncVolume',
            replication__pb2.ResyncVolumeRequest.SerializeToString,
            replication__pb2.ResyncVolumeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetVolumeReplicationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/replication.Controller/GetVolumeReplicationInfo',
            replication__pb2.GetVolumeReplicationInfoRequest.SerializeToString,
            replication__pb2.GetVolumeReplicationInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
