# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vast_extensions.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'vast_extensions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15vast_extensions.proto\x12\x11vastextensions.v1\"4\n\x1bGetReplicationTenantRequest\x12\x15\n\rstorage_class\x18\x01 \x01(\t\"J\n\x1cGetReplicationTenantResponse\x12\x15\n\rstorage_class\x18\x01 \x01(\t\x12\x13\n\x0btenant_guid\x18\x02 \x01(\t\"E\n\x19GetReplicationInfoRequest\x12\x15\n\rstorage_class\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\"\xc2\x01\n\x1aGetReplicationInfoResponse\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\t\x12\x15\n\rresource_kind\x18\x03 \x01(\t\x12\x12\n\nis_primary\x18\x04 \x01(\x08\x12\x17\n\x0fstorage_classes\x18\x05 \x03(\t\x12\x36\n\rfailover_type\x18\x06 \x01(\x0e\x32\x1f.vastextensions.v1.FailoverType*H\n\x0c\x46\x61iloverType\x12\x1c\n\x18\x46\x41ILOVER_TYPE_UNGRACEFUL\x10\x00\x12\x1a\n\x16\x46\x41ILOVER_TYPE_GRACEFUL\x10\x01\x32\xfc\x01\n\x0eVastExtensions\x12w\n\x14GetReplicationTenant\x12..vastextensions.v1.GetReplicationTenantRequest\x1a/.vastextensions.v1.GetReplicationTenantResponse\x12q\n\x12GetReplicationInfo\x12,.vastextensions.v1.GetReplicationInfoRequest\x1a-.vastextensions.v1.GetReplicationInfoResponseB`Z^github.com/vast-data/vast-csi/extensions-controller/internal/server/extensions/v1;extensionsv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vast_extensions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z^github.com/vast-data/vast-csi/extensions-controller/internal/server/extensions/v1;extensionsv1'
  _globals['_FAILOVERTYPE']._serialized_start=442
  _globals['_FAILOVERTYPE']._serialized_end=514
  _globals['_GETREPLICATIONTENANTREQUEST']._serialized_start=44
  _globals['_GETREPLICATIONTENANTREQUEST']._serialized_end=96
  _globals['_GETREPLICATIONTENANTRESPONSE']._serialized_start=98
  _globals['_GETREPLICATIONTENANTRESPONSE']._serialized_end=172
  _globals['_GETREPLICATIONINFOREQUEST']._serialized_start=174
  _globals['_GETREPLICATIONINFOREQUEST']._serialized_end=243
  _globals['_GETREPLICATIONINFORESPONSE']._serialized_start=246
  _globals['_GETREPLICATIONINFORESPONSE']._serialized_end=440
  _globals['_VASTEXTENSIONS']._serialized_start=517
  _globals['_VASTEXTENSIONS']._serialized_end=769
# @@protoc_insertion_point(module_scope)
