# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import vast_extensions_pb2 as vast__extensions__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vast_extensions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VastExtensionsStub(object):
    """VastExtensions exposes management operations to non-native clients
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReplicationTenant = channel.unary_unary(
                '/vastextensions.v1.VastExtensions/GetReplicationTenant',
                request_serializer=vast__extensions__pb2.GetReplicationTenantRequest.SerializeToString,
                response_deserializer=vast__extensions__pb2.GetReplicationTenantResponse.FromString,
                _registered_method=True)
        self.GetReplicationInfo = channel.unary_unary(
                '/vastextensions.v1.VastExtensions/GetReplicationInfo',
                request_serializer=vast__extensions__pb2.GetReplicationInfoRequest.SerializeToString,
                response_deserializer=vast__extensions__pb2.GetReplicationInfoResponse.FromString,
                _registered_method=True)
        self.ResolveSecret = channel.unary_unary(
                '/vastextensions.v1.VastExtensions/ResolveSecret',
                request_serializer=vast__extensions__pb2.ResolveSecretRequest.SerializeToString,
                response_deserializer=vast__extensions__pb2.ResolveSecretResponse.FromString,
                _registered_method=True)
        self.ResolveCOSIBucketAuth = channel.unary_unary(
                '/vastextensions.v1.VastExtensions/ResolveCOSIBucketAuth',
                request_serializer=vast__extensions__pb2.ResolveCOSIBucketAuthRequest.SerializeToString,
                response_deserializer=vast__extensions__pb2.ResolveSecretResponse.FromString,
                _registered_method=True)


class VastExtensionsServicer(object):
    """VastExtensions exposes management operations to non-native clients
    """

    def GetReplicationTenant(self, request, context):
        """GetReplicationTenant resolves the VAST tenant GUID for the given
        Kubernetes StorageClass.  The GUID is looked up from the VAST VMS REST
        API via the VIP pool referenced by the StorageClass parameters
        (vip_pool_name or vip_pool_fqdn).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplicationInfo(self, request, context):
        """GetReplicationInfo - return replication related info.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveSecret(self, request, context):
        """ResolveSecret fetches a Kubernetes Secret and returns its data as a
        key/value map, matching CSI CreateVolumeRequest.secrets as populated by
        the external-provisioner sidecar.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolveCOSIBucketAuth(self, request, context):
        """ResolveCOSIBucketAuth resolves VMS credentials for a COSI bucket_id by
        looking up the Bucket CR and resolving vastdata.com/secret-* parameters.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VastExtensionsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReplicationTenant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicationTenant,
                    request_deserializer=vast__extensions__pb2.GetReplicationTenantRequest.FromString,
                    response_serializer=vast__extensions__pb2.GetReplicationTenantResponse.SerializeToString,
            ),
            'GetReplicationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplicationInfo,
                    request_deserializer=vast__extensions__pb2.GetReplicationInfoRequest.FromString,
                    response_serializer=vast__extensions__pb2.GetReplicationInfoResponse.SerializeToString,
            ),
            'ResolveSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveSecret,
                    request_deserializer=vast__extensions__pb2.ResolveSecretRequest.FromString,
                    response_serializer=vast__extensions__pb2.ResolveSecretResponse.SerializeToString,
            ),
            'ResolveCOSIBucketAuth': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolveCOSIBucketAuth,
                    request_deserializer=vast__extensions__pb2.ResolveCOSIBucketAuthRequest.FromString,
                    response_serializer=vast__extensions__pb2.ResolveSecretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vastextensions.v1.VastExtensions', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vastextensions.v1.VastExtensions', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VastExtensions(object):
    """VastExtensions exposes management operations to non-native clients
    """

    @staticmethod
    def GetReplicationTenant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vastextensions.v1.VastExtensions/GetReplicationTenant',
            vast__extensions__pb2.GetReplicationTenantRequest.SerializeToString,
            vast__extensions__pb2.GetReplicationTenantResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplicationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vastextensions.v1.VastExtensions/GetReplicationInfo',
            vast__extensions__pb2.GetReplicationInfoRequest.SerializeToString,
            vast__extensions__pb2.GetReplicationInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vastextensions.v1.VastExtensions/ResolveSecret',
            vast__extensions__pb2.ResolveSecretRequest.SerializeToString,
            vast__extensions__pb2.ResolveSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolveCOSIBucketAuth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vastextensions.v1.VastExtensions/ResolveCOSIBucketAuth',
            vast__extensions__pb2.ResolveCOSIBucketAuthRequest.SerializeToString,
            vast__extensions__pb2.ResolveSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
