# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import volumegroup_pb2 as volumegroup__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in volumegroup_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControllerStub(object):
    """Controller holds the RPC methods for volumeGroup and all the methods it
    exposes should be idempotent.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateVolumeGroup = channel.unary_unary(
                '/volumegroup.Controller/CreateVolumeGroup',
                request_serializer=volumegroup__pb2.CreateVolumeGroupRequest.SerializeToString,
                response_deserializer=volumegroup__pb2.CreateVolumeGroupResponse.FromString,
                _registered_method=True)
        self.ModifyVolumeGroupMembership = channel.unary_unary(
                '/volumegroup.Controller/ModifyVolumeGroupMembership',
                request_serializer=volumegroup__pb2.ModifyVolumeGroupMembershipRequest.SerializeToString,
                response_deserializer=volumegroup__pb2.ModifyVolumeGroupMembershipResponse.FromString,
                _registered_method=True)
        self.DeleteVolumeGroup = channel.unary_unary(
                '/volumegroup.Controller/DeleteVolumeGroup',
                request_serializer=volumegroup__pb2.DeleteVolumeGroupRequest.SerializeToString,
                response_deserializer=volumegroup__pb2.DeleteVolumeGroupResponse.FromString,
                _registered_method=True)
        self.ListVolumeGroups = channel.unary_unary(
                '/volumegroup.Controller/ListVolumeGroups',
                request_serializer=volumegroup__pb2.ListVolumeGroupsRequest.SerializeToString,
                response_deserializer=volumegroup__pb2.ListVolumeGroupsResponse.FromString,
                _registered_method=True)
        self.ControllerGetVolumeGroup = channel.unary_unary(
                '/volumegroup.Controller/ControllerGetVolumeGroup',
                request_serializer=volumegroup__pb2.ControllerGetVolumeGroupRequest.SerializeToString,
                response_deserializer=volumegroup__pb2.ControllerGetVolumeGroupResponse.FromString,
                _registered_method=True)


class ControllerServicer(object):
    """Controller holds the RPC methods for volumeGroup and all the methods it
    exposes should be idempotent.
    """

    def CreateVolumeGroup(self, request, context):
        """CreateVolumeGroup RPC call to create a volume group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyVolumeGroupMembership(self, request, context):
        """ModifyVolumeGroupMembership RPC call to modify a volume group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteVolumeGroup(self, request, context):
        """DeleteVolumeGroup RPC call to delete a volume group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListVolumeGroups(self, request, context):
        """ListVolumeGroups RPC call to list volume groups.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ControllerGetVolumeGroup(self, request, context):
        """ControllerGetVolumeGroup RPC call to get a volume group.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControllerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateVolumeGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateVolumeGroup,
                    request_deserializer=volumegroup__pb2.CreateVolumeGroupRequest.FromString,
                    response_serializer=volumegroup__pb2.CreateVolumeGroupResponse.SerializeToString,
            ),
            'ModifyVolumeGroupMembership': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyVolumeGroupMembership,
                    request_deserializer=volumegroup__pb2.ModifyVolumeGroupMembershipRequest.FromString,
                    response_serializer=volumegroup__pb2.ModifyVolumeGroupMembershipResponse.SerializeToString,
            ),
            'DeleteVolumeGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteVolumeGroup,
                    request_deserializer=volumegroup__pb2.DeleteVolumeGroupRequest.FromString,
                    response_serializer=volumegroup__pb2.DeleteVolumeGroupResponse.SerializeToString,
            ),
            'ListVolumeGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.ListVolumeGroups,
                    request_deserializer=volumegroup__pb2.ListVolumeGroupsRequest.FromString,
                    response_serializer=volumegroup__pb2.ListVolumeGroupsResponse.SerializeToString,
            ),
            'ControllerGetVolumeGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.ControllerGetVolumeGroup,
                    request_deserializer=volumegroup__pb2.ControllerGetVolumeGroupRequest.FromString,
                    response_serializer=volumegroup__pb2.ControllerGetVolumeGroupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'volumegroup.Controller', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('volumegroup.Controller', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Controller(object):
    """Controller holds the RPC methods for volumeGroup and all the methods it
    exposes should be idempotent.
    """

    @staticmethod
    def CreateVolumeGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volumegroup.Controller/CreateVolumeGroup',
            volumegroup__pb2.CreateVolumeGroupRequest.SerializeToString,
            volumegroup__pb2.CreateVolumeGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyVolumeGroupMembership(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volumegroup.Controller/ModifyVolumeGroupMembership',
            volumegroup__pb2.ModifyVolumeGroupMembershipRequest.SerializeToString,
            volumegroup__pb2.ModifyVolumeGroupMembershipResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteVolumeGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volumegroup.Controller/DeleteVolumeGroup',
            volumegroup__pb2.DeleteVolumeGroupRequest.SerializeToString,
            volumegroup__pb2.DeleteVolumeGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListVolumeGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volumegroup.Controller/ListVolumeGroups',
            volumegroup__pb2.ListVolumeGroupsRequest.SerializeToString,
            volumegroup__pb2.ListVolumeGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ControllerGetVolumeGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/volumegroup.Controller/ControllerGetVolumeGroup',
            volumegroup__pb2.ControllerGetVolumeGroupRequest.SerializeToString,
            volumegroup__pb2.ControllerGetVolumeGroupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
