{{- if ne (toString .Values.olmBuild) "true" }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: vast-csi-driver-operator-controller-manager
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}

---

# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vast-csi-operator-leader-election-role
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
rules:
  {{ include "csi-operator.rbac.leader-election" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vast-csi-operator-manager-role
rules:
  {{ include "csi-operator.rbac.manager" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vast-csi-operator-proxy-role
rules:
  {{ include "csi-operator.rbac.proxy" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vast-csi-operator-leader-election-rolebinding
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vast-csi-operator-leader-election-role
subjects:
  - kind: ServiceAccount
    name: vast-csi-driver-operator-controller-manager
    namespace: {{ .Values.namespace | default .Release.Namespace | quote }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vast-csi-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vast-csi-operator-manager-role
subjects:
  - kind: ServiceAccount
    name: vast-csi-driver-operator-controller-manager
    namespace: {{ .Values.namespace | default .Release.Namespace | quote }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vast-csi-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vast-csi-operator-proxy-role
subjects:
  - kind: ServiceAccount
    name: vast-csi-driver-operator-controller-manager
    namespace: {{ .Values.namespace | default .Release.Namespace | quote }}

---

{{- end -}}
