{{/* Resources description, API spec etc. */}}
{{- $storage_values := dict "Values" (.Files.Get "crd-charts/vaststorage/values.yaml" | trim | fromYaml) "GlobalValues" .Values -}}
{{- $storage_spec := tpl (.Files.Get "crd-charts/vaststorage/values.schema.yaml") $storage_values | trim | fromYaml -}}

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: vaststorages.storage.vastdata.com
spec:
  group: storage.vastdata.com
  names:
    kind: VastStorage
    listKind: VastStorageList
    plural: vaststorages
    singular: vaststorage
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - description: Secret
          jsonPath: .spec.secretName
          name: Secret
          type: string
        - description: Storage Class
          jsonPath: .spec.storageClass.name
          name: StorageClass
          type: string
        - description: Snapshot Class
          jsonPath: .spec.snapshotClass.name
          name: SnapshotClass
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          description: VastStorage is the Schema for the vaststorages API
          properties:
            apiVersion:
              description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
              type: string
            kind:
              description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
              type: string
            metadata:
              type: object
            spec: {{- $storage_spec.spec | toYamlPretty | nindent 14 }}
            status:
              description: Status defines the observed state of VastStorage
              type: object
              x-kubernetes-preserve-unknown-fields: true
          type: object
      served: true
      storage: true
      subresources:
        status: {}
