apiVersion: v1
kind: Pod
metadata:
  name: csi-fs
spec:
  containers:
    - name: app-container
      image: nginx
      volumeMounts:
        - name: data
          mountPath: /mnt/data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: csi-fs
