apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-block-clone
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: vastdata-filesystem
  dataSource:
    name: csi-block
    kind: PersistentVolumeClaim
