apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vastdata-filesystem
parameters:
  csi.storage.k8s.io/controller-expand-secret-name: vast-mgmt
  csi.storage.k8s.io/controller-expand-secret-namespace: default
  csi.storage.k8s.io/controller-publish-secret-name: vast-mgmt
  csi.storage.k8s.io/controller-publish-secret-namespace: default
  csi.storage.k8s.io/node-expand-secret-name: vast-mgmt
  csi.storage.k8s.io/node-expand-secret-namespace: default
  csi.storage.k8s.io/node-publish-secret-name: vast-mgmt
  csi.storage.k8s.io/node-publish-secret-namespace: default
  csi.storage.k8s.io/node-stage-secret-name: vast-mgmt
  csi.storage.k8s.io/node-stage-secret-namespace: default
  csi.storage.k8s.io/provisioner-secret-name: vast-mgmt
  csi.storage.k8s.io/provisioner-secret-namespace: default
  fsType: xfs
  host_encryption: '{"cipher":"aes-xts-plain64","hash":"sha512","key_size":"256","pbkdf_memory":"32768","perf-no_read_workqueue":false,"perf-no_write_workqueue":false,"perf-same_cpu_crypt":false,"perf-submit_from_crypt_cpus":false}'
  subsystem: myblock
  vip_pool_fqdn_random_prefix: "true"
  vip_pool_name: vippool-1
provisioner: block.csi.vastdata.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
