apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-pv-static
spec:
  storageClassName: vastdata-filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  csi:
    driver: block.csi.vastdata.com
    volumeAttributes:
      vip_pool_name: vippool-1  # or vip_pool_fqdn
      subsystem: myblock
    controllerPublishSecretRef:
      name: vast-mgmt
      namespace: default
    volumeHandle: /static/volume

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-static
spec:
  storageClassName: vastdata-filesystem
  volumeName: csi-pv-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
