apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: raw-pv-snapshot
spec:
  snapshotClassName: csi-vast-snapclass
  source:
    name: pvc-raw
    kind: PersistentVolumeClaim
