apiVersion: v1
kind: Pod
metadata:
  name: my-csi-app-inline-bucket-volume
spec:
  containers:
    - name: my-frontend
      image: busybox
      command: ["sleep", "100000"]
      volumeMounts:
        - mountPath: /data
          name: my-csi-volume
  volumes:
    - name: my-csi-volume
      csi:
        driver: csi.vastdata.com
        volumeAttributes:
          bucket_name: my-existing-bucket
          mount_options: vers=4.1
          vip_pool_name: vippool-1
        nodePublishSecretRef:
          name: vast-mgmt
