apiVersion: v1
kind: Pod
metadata:
  name: some-pod
spec:
  containers:
  - command:
    - sh
    - -c
    - while true; do date -Iseconds >> /shared/$HOSTNAME; sleep 1; done
    image: busybox
    name: my-frontend
    volumeMounts:
    - mountPath: /shared
      name: my-eph-vol
  volumes:
  - csi:
      driver: csi.vastdata.com
      volumeAttributes:
        root_export: /k8s
        size: 1G
        view_policy: default
        vip_pool_name: vippool-1
      nodePublishSecretRef:
        name: vast-mgmt
    name: my-eph-vol
