apiVersion: v1
kind: PersistentVolume
metadata:
  name: csi-pv-static
spec:
  storageClassName: vastdata-filesystem
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  mountOptions:
    - nfsvers=3
  csi:
    driver: csi.vastdata.com
    volumeAttributes:
      vip_pool_name: vippool-1  # or vip_pool_fqdn
      view_policy: default  #  needed only when `static_pv_create_views` is set to "yes/true"
      size: 1G
      static_pv_create_views: "yes"
      static_pv_create_quotas: "yes"
    controllerPublishSecretRef:
      name: vast-mgmt
      namespace: default
    volumeHandle: /full/path/to/view

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc-static
spec:
  storageClassName: vastdata-filesystem
  volumeName: csi-pv-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
