{{- if eq .Values.driverType "block" }}

{{/* Validate storagePath parameter. Parameter should not be an empty string. */}}
{{- $is_default_class := .Values.setDefaultStorageClass | default false | quote -}}
{{- $subsystem := .Values.subsystem -}}
{{- if not $subsystem -}}
  {{- fail "subsystem is required value. Please specify valid subsystem" -}}
{{- end }}

{{/* Validate vipPool and vipPoolFQDN parameters. Only one of them should be provided. */}}
{{- $vip_pool_name := .Values.vipPool -}}
{{- $vip_pool_fqdn := .Values.vipPoolFQDN -}}
{{- $vip_pool_fqdn_random_prefix := .Values.vipPoolFQDNRandomPrefix -}}
{{- if (and $vip_pool_name $vip_pool_fqdn) -}}
  {{- fail (printf "vipPool and vipPoolFQDN are mutually exclusive in the StorageClass '%s' parameters. Do not set a default value from storageDefaults for either field; choose only one to specify." .Release.Name) -}}
{{- end }}

{{- $volume_group := .Values.volumeGroup -}}
{{- $fstype := .Values.fsType -}}
{{- $transport_type := .Values.transportType -}}

{{- $volume_name_fmt := .Values.volumeNameFormat -}}
{{- $eph_volume_name_fmt := .Values.ephemeralVolumeNameFormat -}}
{{- $mount_options := .Values.mountOptions -}}
{{- $reclaim_policy := .Values.reclaimPolicy -}}
{{- $allow_volume_expansion := .Values.allowVolumeExpansion | quote | mustRegexMatch "true" | ternary true false -}}

kind: StorageClass
apiVersion: storage.k8s.io/v1
provisioner: {{ include "vastcsi.csiDriver" $ }}
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "vastcsi.namespace" $ }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $is_default_class }}
  labels:
    {{- include "vastcsi.labels" $ | nindent 4 }}
reclaimPolicy: {{ $reclaim_policy }}
parameters:
  subsystem: {{ $subsystem }}
  volume_name_fmt: {{ $volume_name_fmt }}
  eph_volume_name_fmt: {{ $eph_volume_name_fmt }}
{{- range $key, $value := dict "vip_pool_name" $vip_pool_name "vip_pool_fqdn" $vip_pool_fqdn "volume_group" $volume_group "transport_type" $transport_type "fsType" $fstype "vip_pool_fqdn_random_prefix" $vip_pool_fqdn_random_prefix }}
  {{- if and $value (ne $value "") }}
  {{ $key }}: {{ if (kindIs "int" $value) }}{{ $value | quote }}{{ else }}{{ $value }}{{ end }}
  {{- end }}
{{- end }}
  csi.storage.k8s.io/provisioner-secret-name: {{ include "vastcsi.secret" $ }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-publish-secret-name: {{ include "vastcsi.secret" $ }}
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ include "vastcsi.secret" $ }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ include "vastcsi.secret" $ }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ .Release.Namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ include "vastcsi.secret" $ }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ .Release.Namespace }}
allowVolumeExpansion: {{ $allow_volume_expansion }}
{{- if kindIs "string" $mount_options -}}
{{/* Keep option to specify mountOptions as string for backward compatibility */}}
mountOptions:
  - {{ $mount_options | quote }}
{{- else }}
mountOptions: {{ toYaml $mount_options | nindent 2 }}
{{- end }}
---

{{- end }}
