{{- if eq (toString .Values.createSnapshotClass) "true" }}

{{- $is_default_class := .Values.snapshotClass.setDefaultSnapshotClass | default true | quote -}}
{{- $snapshot_name_fmt := .Values.snapshotClass.snapshotNameFormat -}}
{{- $deletion_policy := .Values.snapshotClass.deletionPolicy -}}

apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Release.Name | replace "." "-" }}
  namespace: {{ include "vastcsi.namespace" $ }}
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: {{ $is_default_class }}
  labels:
    {{- include "vastcsi.labels" $ | nindent 4 }}
driver: {{ include "vastcsi.csiDriver" $ }}
deletionPolicy: {{ $deletion_policy }}
parameters:
  snapshot_name_fmt: {{ $snapshot_name_fmt }}
{{- include "vastcsi.snapshotClassSecrets" . | nindent 2 }}
---

{{- end }}
