#!/usr/bin/env bash
# Generates charts/*/templates/replication.yaml:
#   - CSI-Addons operator stack (CRDs, RBAC, controller) from upstream release YAML
#   - VAST extension CRDs from config/crd/bases/
#
# Targets:
#   - charts/vastcsi/templates/replication.yaml
#   - charts/vastblock/templates/replication.yaml
#   - charts/vastcsi-operator/crd-charts/vastcsidriver/templates/replication.yaml
#
# Helm-templated fields in the controller deployment:
#   - extensions.replication.csiAddonsImage
#   - extensions.replication.maxGroupPvcs  (--max-group-pvc flag)
#   - extensionController.resources.csiAddonsClusterManager (container resources)
#
# Run via:  make sync-chart-crds  (from extensions-controller/)
# Or:       ./hack/sync-chart-crds.sh
set -euo pipefail

CSI_ADDONS_VERSION="${CSI_ADDONS_VERSION:-v0.14.0}"
CRD_DIR="config/crd/bases"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

BASE_URL="https://github.com/csi-addons/kubernetes-csi-addons/releases/download/${CSI_ADDONS_VERSION}"
echo "Fetching CSI-Addons ${CSI_ADDONS_VERSION} manifests..."
curl -fsSL "${BASE_URL}/crds.yaml" -o "${TMPDIR}/crds.yaml"
curl -fsSL "${BASE_URL}/rbac.yaml" -o "${TMPDIR}/rbac.yaml"
curl -fsSL "${BASE_URL}/setup-controller.yaml" -o "${TMPDIR}/setup-controller-upstream.yaml"

patch_setup_controller() {
    local src="$1"
    local dest="$2"
    local image_tpl="$3"
    python3 <<PY
from pathlib import Path
import re

setup = Path("${src}")
text = setup.read_text()
needle = "        - --automaxprocs\n"
insert = (
    needle
    + "        - --max-group-pvc={{ .Values.extensions.replication.maxGroupPvcs | default 10000 }}\n"
)
if needle not in text:
    raise SystemExit("setup-controller.yaml: expected --automaxprocs arg not found")
text = text.replace(needle, insert, 1)

image_tpl = """${image_tpl}"""
text, n = re.subn(
    r"^\s*image: quay\.io/csiaddons/k8s-controller:[^\n]+$",
    image_tpl,
    text,
    count=1,
    flags=re.MULTILINE,
)
if n != 1:
    raise SystemExit(f"setup-controller.yaml: expected 1 image line, replaced {n}")

resources_re = re.compile(
    r"^        resources:\n(?:          .+\n)+",
    re.MULTILINE,
)
resources_tpl = (
    "        resources: {{- toYaml .Values.extensionController.resources.csiAddonsClusterManager | nindent 10 }}\n"
)
text, n = resources_re.subn(resources_tpl, text, count=1)
if n != 1:
    raise SystemExit(f"setup-controller.yaml: expected 1 resources block, replaced {n}")
Path("${dest}").write_text(text)
PY
}

IMAGE_TPL_DEFAULT='        image: {{ .Values.extensions.replication.csiAddonsImage | default "quay.io/csiaddons/k8s-controller:v0.14.0" }}'
IMAGE_TPL_OPERATOR='        image: {{ .Values.extensions.replication.csiAddonsImage }}'

patch_setup_controller \
    "${TMPDIR}/setup-controller-upstream.yaml" \
    "${TMPDIR}/setup-controller.yaml" \
    "${IMAGE_TPL_DEFAULT}"
patch_setup_controller \
    "${TMPDIR}/setup-controller-upstream.yaml" \
    "${TMPDIR}/setup-controller-operator.yaml" \
    "${IMAGE_TPL_OPERATOR}"

write_replication_yaml() {
    local dest="$1"
    local if_helper="$2"
    local header_note="$3"
    local setup_file="$4"
    local csi_addons_if='{{- if include "'"${if_helper}"'" . }}'
    local vast_if='{{- if include "'"${if_helper}"'" . }}'

    {
        cat <<EOF
{{- /*
  ${header_note}
  CSI-Addons operator: upstream ${CSI_ADDONS_VERSION} release YAML (auto-generated).
  Templated from values: replication.csiAddonsImage, replication.maxGroupPvcs, extensionController.resources.csiAddonsClusterManager
  VAST CRDs: auto-generated by "make sync-chart-crds". DO NOT EDIT generated sections manually.
*/}}
${csi_addons_if}
# BEGIN AUTO-GENERATED CSI-ADDONS STACK ${CSI_ADDONS_VERSION}
EOF
        cat "${TMPDIR}/crds.yaml"
        echo "---"
        cat "${TMPDIR}/rbac.yaml"
        echo "---"
        cat "${setup_file}"
        cat <<'EOF'
# END AUTO-GENERATED CSI-ADDONS STACK
{{- end }}

# BEGIN AUTO-GENERATED VAST CRDS
EOF
        for f in "${CRD_DIR}"/*.yaml; do
            echo ''
            echo "${vast_if}"
            cat "$f"
            echo '{{- end }}'
        done
        echo ''
        echo '# END AUTO-GENERATED VAST CRDS'
    } > "$dest"
    echo "  ✓  ${dest}  ←  ${CSI_ADDONS_VERSION} + ${CRD_DIR}"
}

write_replication_yaml \
    "../charts/vastblock/templates/replication.yaml" \
    "vastcsi.extension-enabled" \
    "Replication stack installed when extensions are enabled." \
    "${TMPDIR}/setup-controller.yaml"

write_replication_yaml \
    "../charts/vastcsi/templates/replication.yaml" \
    "vastcsi.extension-enabled" \
    "Replication stack installed when extensions are enabled." \
    "${TMPDIR}/setup-controller.yaml"

write_replication_yaml \
    "../charts/vastcsi-operator/crd-charts/vastcsidriver/templates/replication.yaml" \
    "vastcsi.replication-enabled" \
    "Replication stack installed when extensions.replication.enabled is true." \
    "${TMPDIR}/setup-controller-operator.yaml"
