#!/usr/bin/env bash
# Generates charts/*/templates/replication.yaml:
#   - CSI-Addons operator stack (CRDs, RBAC, controller) from upstream release YAML
#   - VAST extension CRDs from config/crd/bases/
#
# Helm-templated fields in the controller deployment:
#   - extensions.replication.csiAddonsImage
#   - extensions.replication.maxGroupPvcs  (--max-group-pvc flag)
#   - extensionController.resources.csiAddonsClusterManager (container resources)
#
# Run via:  make sync-chart-crds  (from extensions-controller/)
# Or:       ./hack/sync-chart-crds.sh
set -euo pipefail

CSI_ADDONS_VERSION="${CSI_ADDONS_VERSION:-v0.14.0}"
CRD_DIR="config/crd/bases"
CHARTS=(
    "../charts/vastblock/templates/replication.yaml"
    "../charts/vastcsi/templates/replication.yaml"
)
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

BASE_URL="https://github.com/csi-addons/kubernetes-csi-addons/releases/download/${CSI_ADDONS_VERSION}"
echo "Fetching CSI-Addons ${CSI_ADDONS_VERSION} manifests..."
curl -fsSL "${BASE_URL}/crds.yaml" -o "${TMPDIR}/crds.yaml"
curl -fsSL "${BASE_URL}/rbac.yaml" -o "${TMPDIR}/rbac.yaml"
curl -fsSL "${BASE_URL}/setup-controller.yaml" -o "${TMPDIR}/setup-controller.yaml"

python3 <<PY
from pathlib import Path

setup = Path("${TMPDIR}/setup-controller.yaml")
text = setup.read_text()
needle = "        - --automaxprocs\n"
insert = (
    needle
    + "        - --max-group-pvc={{ .Values.extensions.replication.maxGroupPvcs | default 10000 }}\n"
)
if needle not in text:
    raise SystemExit("setup-controller.yaml: expected --automaxprocs arg not found")
text = text.replace(needle, insert, 1)

import re
text, n = re.subn(
    r"^\s*image: quay\.io/csiaddons/k8s-controller:[^\n]+$",
    '        image: {{ .Values.extensions.replication.csiAddonsImage | default "quay.io/csiaddons/k8s-controller:v0.14.0" }}',
    text,
    count=1,
    flags=re.MULTILINE,
)
if n != 1:
    raise SystemExit(f"setup-controller.yaml: expected 1 image line, replaced {n}")

resources_re = re.compile(
    r"^        resources:\n(?:          .+\n)+",
    re.MULTILINE,
)
resources_tpl = (
    "        resources: {{- toYaml .Values.extensionController.resources.csiAddonsClusterManager | nindent 10 }}\n"
)
text, n = resources_re.subn(resources_tpl, text, count=1)
if n != 1:
    raise SystemExit(f"setup-controller.yaml: expected 1 resources block, replaced {n}")
setup.write_text(text)
PY

CSI_ADDONS_IF='{{- if include "vastcsi.extension-enabled" . }}'
VAST_IF='{{- if include "vastcsi.extension-enabled" . }}'

for dest in "${CHARTS[@]}"; do
    {
        cat <<EOF
{{- /*
  Replication stack installed when extensions are enabled.
  CSI-Addons operator: upstream ${CSI_ADDONS_VERSION} release YAML (auto-generated).
  Templated from values: replication.csiAddonsImage, replication.maxGroupPvcs, extensionController.resources.csiAddonsClusterManager
  VAST CRDs: auto-generated by "make sync-chart-crds". DO NOT EDIT generated sections manually.
*/}}
${CSI_ADDONS_IF}
# BEGIN AUTO-GENERATED CSI-ADDONS STACK ${CSI_ADDONS_VERSION}
EOF
        cat "${TMPDIR}/crds.yaml"
        echo "---"
        cat "${TMPDIR}/rbac.yaml"
        echo "---"
        cat "${TMPDIR}/setup-controller.yaml"
        cat <<'EOF'
# END AUTO-GENERATED CSI-ADDONS STACK
{{- end }}

# BEGIN AUTO-GENERATED VAST CRDS
EOF
        for f in "${CRD_DIR}"/*.yaml; do
            echo ''
            echo "${VAST_IF}"
            cat "$f"
            echo '{{- end }}'
        done
        echo ''
        echo '# END AUTO-GENERATED VAST CRDS'
    } > "$dest"
    echo "  ✓  $(basename "$dest")  ←  ${CSI_ADDONS_VERSION} + ${CRD_DIR}"
done
