#!/usr/bin/env bash
# Copies generated CRDs from config/crd/bases/ into both Helm chart templates,
# wrapping each CRD in the "vastcsi.extension-enabled" conditional so they are
# only installed when at least one replication feature is enabled.
#
# Run via:  make sync-chart-crds
# Or:       ./hack/sync-chart-crds.sh  (from extensions-controller/ directory)
set -euo pipefail

CRD_DIR="config/crd/bases"
CHARTS=(
    "../charts/vastblock/templates/replication-crds.yaml"
    "../charts/vastcsi/templates/replication-crds.yaml"
)

for dest in "${CHARTS[@]}"; do
    {
        echo '{{- /*'
        echo '  Replication CRDs – installed when any replication feature is enabled.'
        echo '  Auto-generated by "make sync-chart-crds". DO NOT EDIT manually.'
        echo '*/}}'
        for f in "$CRD_DIR"/*.yaml; do
            echo ''
            echo '{{- if include "vastcsi.extension-enabled" . }}'
            cat "$f"
            echo '{{- end }}'
        done
    } > "$dest"
    echo "  ✓  $(basename "$dest")  ←  $CRD_DIR"
done
