{{/* Generate one or more bucket access classes from 'bucketAccessClasses' section. */}}
{{- range $name, $options := .Values.bucketAccessClasses }}

kind: BucketAccessClass
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: {{ required "A BucketAccessClass name must be not empty" $name }}
  namespace: {{ include "vastcosinamespace" $ }}
  labels:
{{- include "vastcosilabels" $ | nindent 4 }}
driverName: {{ include "vastcosi.csiDriver" $ }}
authenticationType: "KEY"
{{- with omit $options "authenticationType" }}
{{- range $key, $value := . }}
{{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}

---
{{- end }}
