---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-objectstorage-provisioner-role
  namespace: {{ include "vast.common.namespace" . }}
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
rules:
- apiGroups: ["objectstorage.k8s.io"]
  resources: ["buckets", "bucketaccesses", "bucketclaims", "bucketaccessclasses", "buckets/status", "bucketaccesses/status", "bucketclaims/status", "bucketaccessclasses/status"]
  verbs: ["get", "list", "watch", "update", "create", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]
- apiGroups: [""]
  resources: ["secrets", "events"]
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-objectstorage-provisioner-role-binding
  namespace: {{ include "vast.common.namespace" . }}
  labels:
    {{- include "vast.common.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-objectstorage-provisioner-sa
    namespace: {{ include "vast.common.namespace" . }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-objectstorage-provisioner-role
  apiGroup: rbac.authorization.k8s.io

---

{{ include "vast.common.resource.serviceAccount" (dict
  "name" (printf "%s-objectstorage-provisioner-sa" .Release.Name)
  "namespace" (include "vast.common.namespace" .)
  "labels" (include "vast.common.labels" .)
) }}

---
