{{- if .Values.sslCert }}
{{ include "vast.common.resource.sslSecret" (dict
  "name" "csi-vast-ca-bundle"
  "namespace" (include "vast.common.namespace" .)
  "labels" (include "vast.common.labels" .)
  "certificate" .Values.sslCert
) }}
{{- end }}
