apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: csi-pvc-clone
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: vastdata-filesystem
  resources:
    requests:
      storage: 2Gi
  dataSource:
    kind: PersistentVolumeClaim
    name: csi-pvc
