apiVersion: vastdata.vastdata.com/v1alpha1
kind: VastReplicationContent
metadata:
  labels:
    app.kubernetes.io/name: extensions-controller
    app.kubernetes.io/managed-by: kustomize
  name: vastreplicationcontent-sample
spec:
  # TODO(user): Add fields here
