apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
    used-by: vast-csi-driver-operator
    {{- include "vastcsi.labels" $ | nindent 4 }}
type: Opaque
data:
  endpoint: {{ .Values.endpoint | required "Endpoint is required value" | b64enc | quote }}
  {{- if .Values.username }}
  username: {{ .Values.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.password }}
  password: {{ .Values.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.token }}
  token: {{ .Values.token | b64enc | quote }}
  {{- end }}
  {{- if .Values.sslCert }}
  ssl_cert: {{ .Values.sslCert | b64enc | quote }}
  {{- end }}
  {{- if .Values.passphrase }}
  passphrase: {{ .Values.passphrase | b64enc | quote }}
  {{- end }}
