apiVersion: v2
name: vastcosi
description: Helm chart for Deployment of VAST Container Object Storage Interface (COSI)
type: application
version: "0.1.0" #  will be updated by the release ci
keywords:
  - vast
  - csi
  - driver
  - vastdata
  - cosi
  - cosi-driver
icon: "https://uploads.vastdata.com/2020/04/vast-white-1.svg"
home: "https://support.vastdata.com/hc/en-us/articles/8022914098716"
