apiVersion: v2
name: vastcosi
description: Helm chart for Deployment of VAST Container Object Storage Interface (COSI)
type: application
version: "2.6.3" #  will be updated by the release ci
keywords:
  - vast
  - csi
  - driver
  - vastdata
  - cosi
  - cosi-driver
icon: "https://uploads.vastdata.com/2020/04/vast-white-1.svg"
home: "https://support.vastdata.com/s/topic/0TOV400000026yzOAA/vast-csi-driver"