/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DEFS_H_RPCGEN
#define _RPC_DEFS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MACHINE_NAME_LEN 255
#define MAX_GIDS 16
#define AUTH_SIZE 400

struct vauthsys_parms {
	u_int stamp;
	char *machinename;
	u_int uid;
	u_int gid;
	struct {
		u_int gids_len;
		u_int *gids_val;
	} gids;
};
typedef struct vauthsys_parms vauthsys_parms;
#ifdef __cplusplus
extern "C" bool_t xdr_vauthsys_parms(XDR *, vauthsys_parms*);
#elif __STDC__
extern  bool_t xdr_vauthsys_parms(XDR *, vauthsys_parms*);
#else /* Old Style C */
bool_t xdr_vauthsys_parms();
#endif /* Old Style C */


enum vauth_flavor {
	VAUTH_NONE = 0,
	VAUTH_SYS = 1,
	VAUTH_SHORT = 2,
	VAUTH_DH = 3,
	VRPCSEC_GSS = 6,
};
typedef enum vauth_flavor vauth_flavor;
#ifdef __cplusplus
extern "C" bool_t xdr_vauth_flavor(XDR *, vauth_flavor*);
#elif __STDC__
extern  bool_t xdr_vauth_flavor(XDR *, vauth_flavor*);
#else /* Old Style C */
bool_t xdr_vauth_flavor();
#endif /* Old Style C */


struct vopaque_auth {
	vauth_flavor flavor;
	struct {
		u_int body_len;
		char *body_val;
	} body;
};
typedef struct vopaque_auth vopaque_auth;
#ifdef __cplusplus
extern "C" bool_t xdr_vopaque_auth(XDR *, vopaque_auth*);
#elif __STDC__
extern  bool_t xdr_vopaque_auth(XDR *, vopaque_auth*);
#else /* Old Style C */
bool_t xdr_vopaque_auth();
#endif /* Old Style C */


enum vmsg_type {
	VCALL = 0,
	VREPLY = 1,
};
typedef enum vmsg_type vmsg_type;
#ifdef __cplusplus
extern "C" bool_t xdr_vmsg_type(XDR *, vmsg_type*);
#elif __STDC__
extern  bool_t xdr_vmsg_type(XDR *, vmsg_type*);
#else /* Old Style C */
bool_t xdr_vmsg_type();
#endif /* Old Style C */


enum vreply_stat {
	VMSG_ACCEPTED = 0,
	VMSG_DENIED = 1,
};
typedef enum vreply_stat vreply_stat;
#ifdef __cplusplus
extern "C" bool_t xdr_vreply_stat(XDR *, vreply_stat*);
#elif __STDC__
extern  bool_t xdr_vreply_stat(XDR *, vreply_stat*);
#else /* Old Style C */
bool_t xdr_vreply_stat();
#endif /* Old Style C */


enum vaccept_stat {
	VSUCCESS = 0,
	VPROG_UNAVAIL = 1,
	VPROG_MISMATCH = 2,
	VPROC_UNAVAIL = 3,
	VGARBAGE_ARGS = 4,
	VSYSTEM_ERR = 5,
};
typedef enum vaccept_stat vaccept_stat;
#ifdef __cplusplus
extern "C" bool_t xdr_vaccept_stat(XDR *, vaccept_stat*);
#elif __STDC__
extern  bool_t xdr_vaccept_stat(XDR *, vaccept_stat*);
#else /* Old Style C */
bool_t xdr_vaccept_stat();
#endif /* Old Style C */


enum vreject_stat {
	VRPC_MISMATCH = 0,
	VAUTH_ERROR = 1,
};
typedef enum vreject_stat vreject_stat;
#ifdef __cplusplus
extern "C" bool_t xdr_vreject_stat(XDR *, vreject_stat*);
#elif __STDC__
extern  bool_t xdr_vreject_stat(XDR *, vreject_stat*);
#else /* Old Style C */
bool_t xdr_vreject_stat();
#endif /* Old Style C */


enum vauth_stat {
	VAUTH_OK = 0,
	VAUTH_BADCRED = 1,
	VAUTH_REJECTEDCRED = 2,
	VAUTH_BADVERF = 3,
	VAUTH_REJECTEDVERF = 4,
	VAUTH_TOOWEAK = 5,
	VAUTH_INVALIDRESP = 6,
	VAUTH_FAILED = 7,
	VAUTH_KERB_GENERIC = 8,
	VAUTH_TIMEEXPIRE = 9,
	VAUTH_TKT_FILE = 10,
	VAUTH_DECODE = 11,
	VAUTH_NET_ADDR = 12,
	VRPCSEC_GSS_CREDPROBLEM = 13,
	VRPCSEC_GSS_CTXPROBLEM = 14,
};
typedef enum vauth_stat vauth_stat;
#ifdef __cplusplus
extern "C" bool_t xdr_vauth_stat(XDR *, vauth_stat*);
#elif __STDC__
extern  bool_t xdr_vauth_stat(XDR *, vauth_stat*);
#else /* Old Style C */
bool_t xdr_vauth_stat();
#endif /* Old Style C */


struct vmismatch_info {
	u_int low;
	u_int high;
};
typedef struct vmismatch_info vmismatch_info;
#ifdef __cplusplus
extern "C" bool_t xdr_vmismatch_info(XDR *, vmismatch_info*);
#elif __STDC__
extern  bool_t xdr_vmismatch_info(XDR *, vmismatch_info*);
#else /* Old Style C */
bool_t xdr_vmismatch_info();
#endif /* Old Style C */


struct vcall_body {
	u_int rpcvers;
	u_int prog;
	u_int vers;
	u_int proc;
	vopaque_auth cred;
	vopaque_auth verf;
};
typedef struct vcall_body vcall_body;
#ifdef __cplusplus
extern "C" bool_t xdr_vcall_body(XDR *, vcall_body*);
#elif __STDC__
extern  bool_t xdr_vcall_body(XDR *, vcall_body*);
#else /* Old Style C */
bool_t xdr_vcall_body();
#endif /* Old Style C */


struct vreply_data_body {
	vaccept_stat stat;
	union {
		char results[0];
		vmismatch_info m_info;
	} vreply_data_body_u;
};
typedef struct vreply_data_body vreply_data_body;
#ifdef __cplusplus
extern "C" bool_t xdr_vreply_data_body(XDR *, vreply_data_body*);
#elif __STDC__
extern  bool_t xdr_vreply_data_body(XDR *, vreply_data_body*);
#else /* Old Style C */
bool_t xdr_vreply_data_body();
#endif /* Old Style C */


struct vaccepted_reply {
	vopaque_auth verf;
	vreply_data_body reply_data;
};
typedef struct vaccepted_reply vaccepted_reply;
#ifdef __cplusplus
extern "C" bool_t xdr_vaccepted_reply(XDR *, vaccepted_reply*);
#elif __STDC__
extern  bool_t xdr_vaccepted_reply(XDR *, vaccepted_reply*);
#else /* Old Style C */
bool_t xdr_vaccepted_reply();
#endif /* Old Style C */


struct vrejected_reply {
	vreject_stat stat;
	union {
		vmismatch_info m_info;
		vauth_stat stat;
	} vrejected_reply_u;
};
typedef struct vrejected_reply vrejected_reply;
#ifdef __cplusplus
extern "C" bool_t xdr_vrejected_reply(XDR *, vrejected_reply*);
#elif __STDC__
extern  bool_t xdr_vrejected_reply(XDR *, vrejected_reply*);
#else /* Old Style C */
bool_t xdr_vrejected_reply();
#endif /* Old Style C */


struct vreply_body {
	vreply_stat stat;
	union {
		vaccepted_reply areply;
		vrejected_reply rreply;
	} vreply_body_u;
};
typedef struct vreply_body vreply_body;
#ifdef __cplusplus
extern "C" bool_t xdr_vreply_body(XDR *, vreply_body*);
#elif __STDC__
extern  bool_t xdr_vreply_body(XDR *, vreply_body*);
#else /* Old Style C */
bool_t xdr_vreply_body();
#endif /* Old Style C */


struct vrpc_msg_body {
	vmsg_type mtype;
	union {
		vcall_body cbody;
		vreply_body rbody;
	} vrpc_msg_body_u;
};
typedef struct vrpc_msg_body vrpc_msg_body;
#ifdef __cplusplus
extern "C" bool_t xdr_vrpc_msg_body(XDR *, vrpc_msg_body*);
#elif __STDC__
extern  bool_t xdr_vrpc_msg_body(XDR *, vrpc_msg_body*);
#else /* Old Style C */
bool_t xdr_vrpc_msg_body();
#endif /* Old Style C */


struct vrpc_msg {
	u_int xid;
	vrpc_msg_body body;
};
typedef struct vrpc_msg vrpc_msg;
#ifdef __cplusplus
extern "C" bool_t xdr_vrpc_msg(XDR *, vrpc_msg*);
#elif __STDC__
extern  bool_t xdr_vrpc_msg(XDR *, vrpc_msg*);
#else /* Old Style C */
bool_t xdr_vrpc_msg();
#endif /* Old Style C */


#endif /* !_RPC_DEFS_H_RPCGEN */
