/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpc_defs.h"

bool_t
xdr_vauthsys_parms(xdrs, objp)
	XDR *xdrs;
	vauthsys_parms *objp;
{

	if (!xdr_u_int(xdrs, &objp->stamp))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->machinename, MACHINE_NAME_LEN))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->uid))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->gid))
		return (FALSE);
	if (!xdr_array(xdrs, (char **)&objp->gids.gids_val, (u_int *)&objp->gids.gids_len, MAX_GIDS, sizeof(u_int), (xdrproc_t)xdr_u_int))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vauth_flavor(xdrs, objp)
	XDR *xdrs;
	vauth_flavor *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vopaque_auth(xdrs, objp)
	XDR *xdrs;
	vopaque_auth *objp;
{

	if (!xdr_vauth_flavor(xdrs, &objp->flavor))
		return (FALSE);
	if (!xdr_bytes(xdrs, (char **)&objp->body.body_val, (u_int *)&objp->body.body_len, AUTH_SIZE))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vmsg_type(xdrs, objp)
	XDR *xdrs;
	vmsg_type *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vreply_stat(xdrs, objp)
	XDR *xdrs;
	vreply_stat *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vaccept_stat(xdrs, objp)
	XDR *xdrs;
	vaccept_stat *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vreject_stat(xdrs, objp)
	XDR *xdrs;
	vreject_stat *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vauth_stat(xdrs, objp)
	XDR *xdrs;
	vauth_stat *objp;
{

	if (!xdr_enum(xdrs, (enum_t *)objp))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vmismatch_info(xdrs, objp)
	XDR *xdrs;
	vmismatch_info *objp;
{

	if (!xdr_u_int(xdrs, &objp->low))
		return (FALSE);
	if (!xdr_u_int(xdrs, &objp->high))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vcall_body(xdrs, objp)
	XDR *xdrs;
	vcall_body *objp;
{
	int32_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->rpcvers))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->prog))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->vers))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->proc))
				return (FALSE);
		} else {
			IXDR_PUT_U_LONG(buf, objp->rpcvers);
			IXDR_PUT_U_LONG(buf, objp->prog);
			IXDR_PUT_U_LONG(buf, objp->vers);
			IXDR_PUT_U_LONG(buf, objp->proc);
		}
		if (!xdr_vopaque_auth(xdrs, &objp->cred))
			return (FALSE);
		if (!xdr_vopaque_auth(xdrs, &objp->verf))
			return (FALSE);
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_u_int(xdrs, &objp->rpcvers))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->prog))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->vers))
				return (FALSE);
			if (!xdr_u_int(xdrs, &objp->proc))
				return (FALSE);
		} else {
			objp->rpcvers = IXDR_GET_U_LONG(buf);
			objp->prog = IXDR_GET_U_LONG(buf);
			objp->vers = IXDR_GET_U_LONG(buf);
			objp->proc = IXDR_GET_U_LONG(buf);
		}
		if (!xdr_vopaque_auth(xdrs, &objp->cred))
			return (FALSE);
		if (!xdr_vopaque_auth(xdrs, &objp->verf))
			return (FALSE);
	} else {
		if (!xdr_u_int(xdrs, &objp->rpcvers))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->prog))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->vers))
			return (FALSE);
		if (!xdr_u_int(xdrs, &objp->proc))
			return (FALSE);
		if (!xdr_vopaque_auth(xdrs, &objp->cred))
			return (FALSE);
		if (!xdr_vopaque_auth(xdrs, &objp->verf))
			return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_vreply_data_body(xdrs, objp)
	XDR *xdrs;
	vreply_data_body *objp;
{

	if (!xdr_vaccept_stat(xdrs, &objp->stat))
		return (FALSE);
	switch (objp->stat) {
	case VSUCCESS:
		if (!xdr_opaque(xdrs, objp->vreply_data_body_u.results, 0))
			return (FALSE);
		break;
	case VPROG_MISMATCH:
		if (!xdr_vmismatch_info(xdrs, &objp->vreply_data_body_u.m_info))
			return (FALSE);
		break;
	default:
		break;
	}
	return (TRUE);
}

bool_t
xdr_vaccepted_reply(xdrs, objp)
	XDR *xdrs;
	vaccepted_reply *objp;
{

	if (!xdr_vopaque_auth(xdrs, &objp->verf))
		return (FALSE);
	if (!xdr_vreply_data_body(xdrs, &objp->reply_data))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_vrejected_reply(xdrs, objp)
	XDR *xdrs;
	vrejected_reply *objp;
{

	if (!xdr_vreject_stat(xdrs, &objp->stat))
		return (FALSE);
	switch (objp->stat) {
	case VRPC_MISMATCH:
		if (!xdr_vmismatch_info(xdrs, &objp->vrejected_reply_u.m_info))
			return (FALSE);
		break;
	case VAUTH_ERROR:
		if (!xdr_vauth_stat(xdrs, &objp->vrejected_reply_u.stat))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_vreply_body(xdrs, objp)
	XDR *xdrs;
	vreply_body *objp;
{

	if (!xdr_vreply_stat(xdrs, &objp->stat))
		return (FALSE);
	switch (objp->stat) {
	case VMSG_ACCEPTED:
		if (!xdr_vaccepted_reply(xdrs, &objp->vreply_body_u.areply))
			return (FALSE);
		break;
	case VMSG_DENIED:
		if (!xdr_vrejected_reply(xdrs, &objp->vreply_body_u.rreply))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_vrpc_msg_body(xdrs, objp)
	XDR *xdrs;
	vrpc_msg_body *objp;
{

	if (!xdr_vmsg_type(xdrs, &objp->mtype))
		return (FALSE);
	switch (objp->mtype) {
	case VCALL:
		if (!xdr_vcall_body(xdrs, &objp->vrpc_msg_body_u.cbody))
			return (FALSE);
		break;
	case VREPLY:
		if (!xdr_vreply_body(xdrs, &objp->vrpc_msg_body_u.rbody))
			return (FALSE);
		break;
	default:
		return (FALSE);
	}
	return (TRUE);
}

bool_t
xdr_vrpc_msg(xdrs, objp)
	XDR *xdrs;
	vrpc_msg *objp;
{

	if (!xdr_u_int(xdrs, &objp->xid))
		return (FALSE);
	if (!xdr_vrpc_msg_body(xdrs, &objp->body))
		return (FALSE);
	return (TRUE);
}
