{{- $common := dict "namespace" (include "vast.common.namespace" .) "labels" (include "vast.common.labels" .) -}}
{{ include "vast.common.resource.serviceAccount" (merge (dict "name" (printf "%s-vast-controller-sa" .Release.Name)) $common) }}
---
{{ include "vast.common.resource.serviceAccount" (merge (dict "name" (printf "%s-vast-node-sa" .Release.Name)) $common) }}
