{{- if .Values.node.metrics.enabled }}
{{/* Vast CSI Node Metrics Service - selects only this chart's node pods (block driver) */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vast-node-metrics
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
{{- include "vastcsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    app.kubernetes.io/csi-role: "node"
spec:
  type: ClusterIP
  clusterIP: None  # Headless service for DaemonSet
  selector:
    app: csi-vast-node
    csi.vastdata.com/driver: block
{{- include "vastcsi.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.node.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}

---

{{- if .Values.controller.metrics.enabled }}
{{/* Vast CSI Controller Metrics Service - selects only this chart's controller pods (block driver) */}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vast-controller-metrics
  namespace: {{ include "vastcsi.namespace" . }}
  labels:
{{- include "vastcsi.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
    app.kubernetes.io/csi-role: "controller"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: csi-vast-controller
{{- include "vastcsi.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.controller.metrics.port }}
      targetPort: metrics
      protocol: TCP
{{- end }}
