{{/* Generate one or more storage classes from 'storageClasses' section. */}}

{{/* Iterate over StorageClasses from manifest */}}
{{- range $name, $options := .Values.storageClasses }}

{{/* Validate  setDefaultStorageClass option. Options should be either true or false */}}
{{-
    $is_default_class := pluck "setDefaultStorageClass" $options $.Values.storageClassDefaults | first | quote
-}}
{{- if not (or (kindIs "bool" $is_default_class ) ( $is_default_class | mustRegexMatch "true|false" )) -}}
  {{- fail "setDefaultStorageClass should be either 'true' or 'false'" -}}
{{- end }}

{{/* Validate  subsystem parameter. Parameter should be not empty string. */}}
{{- $subsystem := pluck "subsystem" $options $.Values.storageClassDefaults | first | quote -}}
{{- if eq $subsystem ( quote "" ) -}}
  {{- fail "subsystem is required value. Please specify valid subsystem" -}}
{{- end }}

{{- $vip_pool_name := pluck "vipPool" $options $.Values.storageClassDefaults | first | quote -}}
{{- $vip_pool_fqdn := pluck "vipPoolFQDN" $options $.Values.storageClassDefaults | first | quote -}}
{{- $vip_pool_fqdn_random_prefix := pluck "vipPoolFQDNRandomPrefix" $options $.Values.storageClassDefaults | first | quote -}}

{{- if and (ne $vip_pool_name ( quote "" )) (ne $vip_pool_fqdn ( quote "" )) -}}
{{- fail (printf "vipPool and vipPoolFQDN are mutually exclusive in the StorageClass '%s' parameters. Do not set a default value from storageDefaults for either field; choose only one to specify." $name) -}}
{{- end }}

{{- $tenant_name := pluck "tenantName" $options $.Values.storageClassDefaults | first | quote -}}
{{- $volume_group := pluck "volumeGroup" $options $.Values.storageClassDefaults | first | quote -}}
{{- $mount_options :=  pluck "mountOptions" $options $.Values.storageClassDefaults | first -}}
{{- $reclaim_policy :=  pluck "reclaimPolicy" $options $.Values.storageClassDefaults | first | quote -}}
{{-
   $allow_volume_expansion := pluck "allowVolumeExpansion" $options $.Values.storageClassDefaults |
   first | quote | mustRegexMatch "true" | ternary true false
-}}

{{- $storage_class_secret := pluck "secretName" $options $.Values.storageClassDefaults | first | quote -}}
{{/* Get secretNamespace parameter. If not provided .Release.Namespace is used. */}}
{{- $storage_class_secret_namespace := pluck "secretNamespace" $options $.Values.storageClassDefaults | first | default $.Release.Namespace | quote -}}
{{- $fstype := pluck "fsType" $options $.Values.storageClassDefaults | first -}}
{{- $transport_type := pluck "transportType" $options $.Values.storageClassDefaults | first -}}
{{- $qos_policy :=  pluck "qosPolicy" $options $.Values.storageClassDefaults | first | quote -}}
{{- $host_encryption := pluck "hostEncryption" $options $.Values.storageClassDefaults | first | default dict -}}
{{- $blocking_clones := pluck "blockingClones" $options $.Values.storageClassDefaults | first | quote -}}

kind: StorageClass
apiVersion: storage.k8s.io/v1
provisioner: {{ include "vastcsi.csiDriver" $ }}
metadata:
  name: {{ required "A StorageClass name must be not empty" $name }}
  namespace: {{ include "vastcsi.namespace" $ }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ $is_default_class }}
  labels:
  {{- include "vastcsi.labels" $ | nindent 4 }}
reclaimPolicy: {{ $reclaim_policy }}
parameters:

{{- include "vastcsi.dictToKeyValParams" (list (dict
  "subsystem" $subsystem
  "vip_pool_name" $vip_pool_name
  "vip_pool_fqdn" $vip_pool_fqdn
  "volume_group" $volume_group
  "transport_type" $transport_type
  "fsType" $fstype
  "tenant_name" $tenant_name
  "qos_policy" $qos_policy
)) | indent 2 }}

{{- include "vastcsi.dictToBoolParams" (list (dict
  "vip_pool_fqdn_random_prefix" $vip_pool_fqdn_random_prefix
  "blocking_clones" $blocking_clones
)) | indent 2 }}

{{- if $host_encryption }}
{{ include "vastcsi.dictToJsonStringParam" (list $host_encryption "host_encryption") | indent 2 }}
{{- end }}

{{-  if ne $storage_class_secret ( quote "" ) }}
  csi.storage.k8s.io/provisioner-secret-name: {{ $storage_class_secret }}
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $storage_class_secret_namespace }}
  csi.storage.k8s.io/controller-publish-secret-name: {{ $storage_class_secret }}
  csi.storage.k8s.io/controller-publish-secret-namespace: {{ $storage_class_secret_namespace }}
  csi.storage.k8s.io/node-publish-secret-name: {{ $storage_class_secret }}
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $storage_class_secret_namespace }}
  csi.storage.k8s.io/node-stage-secret-name: {{ $storage_class_secret }}
  csi.storage.k8s.io/node-stage-secret-namespace: {{ $storage_class_secret_namespace }}
  csi.storage.k8s.io/controller-expand-secret-name: {{ $storage_class_secret }}
  csi.storage.k8s.io/controller-expand-secret-namespace: {{ $storage_class_secret_namespace }}
  csi.storage.k8s.io/node-expand-secret-name: {{ $storage_class_secret }}
  csi.storage.k8s.io/node-expand-secret-namespace: {{ $storage_class_secret_namespace }}
{{- end }}
allowVolumeExpansion: {{ $allow_volume_expansion }}
{{- if kindIs "string" $mount_options -}}
{{/* Keep option to specify mountOptions as string for backward compatibility */}}
mountOptions:
  - {{ $mount_options | quote }}
{{- else }}
mountOptions: {{ toYaml $mount_options | nindent 2  }}
{{- end }}
---
{{- end }}
