{{- if .Values.extensions.enabled }}
{{ include "vast.common.resource.webhookService" (dict
  "name" (printf "%s-vast-extension-controller-webhook" .Release.Name)
  "namespace" (include "vast.common.namespace" .)
  "labels" (include "vast.common.labels" .)
  "targetPort" .Values.extensions.webhook.port
  "appSelector" "vast-extension-controller"
  "selectorLabels" (include "vast.common.selectorLabels" .)
) }}
{{- end }}
