# VMS credentials for the two-site NFS replication demo.
---
apiVersion: v1
kind: Secret
metadata:
  name: vast-mgmt
  namespace: vast-csi
type: Opaque
stringData:
  endpoint: 10.205.0.233
  username: admin
  password: "123456"
---
apiVersion: v1
kind: Secret
metadata:
  name: vast-mgmt2
  namespace: vast-csi
type: Opaque
stringData:
  endpoint: "16.0.0.2"
  username: admin
  password: "123456"
