name: Release Common Chart

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Configure GitHub CLI
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release vast-common
        run: ./scripts/release_common_chart.sh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_REMOTE: https://github.com/vast-data/vast-csi.git
