name: Release Charts

on: [push]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Prepare releaser configuration
        run: |
          python .github/workflows/prepare_releaser_configuration.py

      - name: Configure Git
        if: ${{ hashFiles('releaser-config.yml') != '' }}
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        if: ${{ hashFiles('releaser-config.yml') != '' }}
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: releaser-config.yml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
