/* Copyright (C) Vast Data Ltd. */

/*!
 * \file object.hpp
 * \brief The metrics object is a base class for all metrics object automatically generated by the parser.
 */
#pragma once

#include "defs.hpp"
#include "tracker.hpp"

namespace P { namespace Metrics {

class Object {
public:
    void init(P::Metrics::Tracker *tracker, Object *parent)
    {
        list_node.init();
        _tracker = tracker;
        _parent = parent;
        _generation = _tracker->next_generation();
        _tracker->on_object_init(this);
    }

    void destroy()
    {
        _tracker->on_object_destroy(this);
    }

    uint64_t get_generation()
    {
        return _generation;
    }

    virtual size_t get_clone_size() = 0;
    virtual size_t clone(void *buffer) = 0;

    IListNode list_node;

protected:
    Tracker *_tracker;
    Object *_parent;
    uint64_t _generation;
};

}}
