/* Copyright (C) Vast Data Ltd. */

/*!
 * \file object.hpp
 * \brief The metrics object is a base class for all metrics object automatically generated by the parser.
 */
#pragma once

#include "defs.hpp"
#include "agent.hpp"

namespace P { namespace Metrics {

class Object {
public:
    void init(P::Metrics::Agent *agent, Object *parent)
    {
        _agent = agent;
        _parent = parent;
        _next = nullptr;
        _generation = _agent->next_generation();
        _agent->on_object_init(this);
    }

    void destroy()
    {
        _agent->on_object_destroy(this);
    }

    void set_next(Object *next)
    {
        _next = next;
    }

    Object *get_next()
    {
        return _next;
    }

    uint64_t get_generation()
    {
        return _generation;
    }

    virtual size_t get_clone_size() = 0;
    virtual size_t clone(void *buffer) = 0;

protected:
    Agent *_agent;
    Object *_next;
    Object *_parent;
    uint64_t _generation;
};

}}
